import Link from 'next/link'
import { Card, EmptyState, PageHeader } from '@/components/ui'
import { TradeForm } from '../trade-form'
import { desc, eq } from 'drizzle-orm'
import { db } from '@/db'
import { propFirms, trades, tradingModels } from '@/db/schema'
import { listAccounts } from '@/server/trades'

export const dynamic = 'force-dynamic'
export const metadata = { title: 'Log a trade — Trading Journal' }

export default async function NewTradePage() {
  const [accounts, models, firms, recent] = await Promise.all([
    listAccounts(),
    db.select().from(tradingModels).where(eq(tradingModels.active, true)).orderBy(tradingModels.name),
    db.select({ id: propFirms.id, name: propFirms.name }).from(propFirms),
    // The accounts the last hand-logged trade went on. A copier set changes far
    // less often than trades are logged, so it is the right default to offer.
    db
      .select({ accountId: trades.accountId, entryAt: trades.entryAt })
      .from(trades)
      .where(eq(trades.autoGenerated, false))
      .orderBy(desc(trades.createdAt))
      .limit(12),
  ])

  const lastEntry = recent[0]?.entryAt?.getTime()
  const lastUsed = lastEntry
    ? [...new Set(recent.filter((row) => row.entryAt?.getTime() === lastEntry).map((row) => row.accountId))]
    : []

  if (accounts.length === 0) {
    return (
      <>
        <PageHeader title="Log a trade" />
        <Card>
          <EmptyState
            title="No accounts yet"
            body="A trade has to belong to an account, so add one first."
            action={{ href: '/accounts', label: 'Add an account' }}
          />
        </Card>
      </>
    )
  }

  return (
    <>
      <PageHeader
        title="Log a trade"
        subtitle="For trades that did not come from a sync or an import. These are kept as your own record and survive a rebuild."
        actions={
          <Link href="/trades" className="btn">
            ← All trades
          </Link>
        }
      />

      <Card className="max-w-3xl">
        <TradeForm accounts={accounts} models={models} firms={firms} lastUsed={lastUsed} />
      </Card>
    </>
  )
}
