import 'server-only'
import { and, asc, desc, eq, gte, inArray, lte, sql } from 'drizzle-orm'
import { db } from '@/db'
import {
  accounts,
  dailyStats,
  executions,
  trades,
  type Account,
  type NewExecution,
  type Trade,
} from '@/db/schema'
import { matchExecutions, rMultiple, type MatchExecution } from '@/lib/analytics/matching'
import { dailySeries, type TradeLike } from '@/lib/analytics/metrics'
import { decryptBytes } from '@/lib/crypto'

/**
 * Rebuilds an account's trades from its executions.
 *
 * Matching is a pure function of the fill history, so the honest way to keep
 * trades correct after a backfill, a correction or a late-arriving fill is to
 * throw the derived rows away and rebuild. Manually-entered trades are left
 * alone — they have no executions behind them and are the user's own record.
 *
 * Annotations the user added (setup, tags, mistakes, notes, stop price) are
 * carried across by matching on entry time and symbol, so a rebuild never
 * costs someone their journalling.
 */
export async function rebuildTradesForAccount(accountId: number): Promise<number> {
  const [account] = await db.select().from(accounts).where(eq(accounts.id, accountId)).limit(1)
  if (!account) return 0

  const fills = await db
    .select()
    .from(executions)
    .where(eq(executions.accountId, accountId))
    .orderBy(asc(executions.fillAt), asc(executions.id))

  if (fills.length === 0) return 0

  const previous = await db
    .select()
    .from(trades)
    .where(and(eq(trades.accountId, accountId), eq(trades.autoGenerated, true)))

  // Key annotations by entry instant + symbol so they survive the rebuild.
  const annotations = new Map<string, Trade>()
  for (const trade of previous) {
    annotations.set(annotationKey(trade.entryAt, trade.symbol), trade)
  }

  const matchInput: MatchExecution[] = fills.map((fill) => ({
    id: fill.id,
    accountId: fill.accountId,
    contract: fill.contract,
    side: fill.side,
    qty: fill.qty,
    fillPrice: fill.fillPrice,
    fillAt: fill.fillAt,
    tradingDay: fill.tradingDay,
    commission: fill.commission,
    fees: fill.fees,
  }))

  const matched = matchExecutions(matchInput)

  await db.transaction(async (tx) => {
    // Detach fills before deleting trades so the FK never dangles mid-transaction.
    await tx
      .update(executions)
      .set({ tradeId: null })
      .where(eq(executions.accountId, accountId))
    await tx.delete(trades).where(and(eq(trades.accountId, accountId), eq(trades.autoGenerated, true)))

    if (matched.length === 0) return

    // One multi-row INSERT and one UPDATE...FROM instead of two round trips
    // per trade. RETURNING preserves input order, so the ids line up with
    // `matched` by index — an account with a thousand trades rebuilds in two
    // statements rather than two thousand, which is the difference between
    // milliseconds and a timed-out cron when the database is a network hop away.
    const rows = matched.map((trade) => {
      const carried = annotations.get(annotationKey(trade.entryAt, trade.symbol))
      const riskBase = carried?.riskBase ?? null
      return {
        accountId: trade.accountId,
        symbol: trade.symbol,
        contract: trade.contract,
        direction: trade.direction,
        qty: trade.qty,
        entryAt: trade.entryAt,
        exitAt: trade.exitAt,
        tradingDay: trade.tradingDay,
        avgEntry: trade.avgEntry,
        avgExit: trade.avgExit,
        grossPnl: trade.grossPnl,
        commission: trade.commission,
        fees: trade.fees,
        netPnl: trade.netPnl,
        durationSeconds: trade.durationSeconds,
        status: trade.status,
        autoGenerated: true,
        stopPrice: carried?.stopPrice ?? null,
        targetPrice: carried?.targetPrice ?? null,
        riskBase,
        rMultiple: rMultiple(trade.netPnl, riskBase),
        setup: carried?.setup ?? null,
        modelId: carried?.modelId ?? null,
        modelReview: carried?.modelReview ?? null,
        tags: carried?.tags ?? [],
        mistakes: carried?.mistakes ?? [],
        execScore: carried?.execScore ?? null,
        emotion: carried?.emotion ?? null,
        notes: carried?.notes ?? null,
        screenshotUrl: carried?.screenshotUrl ?? null,
      }
    })

    const insertedIds = await tx.insert(trades).values(rows).returning({ id: trades.id })

    const pairs: { executionId: number; tradeId: number }[] = []
    matched.forEach((trade, index) => {
      for (const executionId of trade.executionIds) {
        pairs.push({ executionId, tradeId: insertedIds[index].id })
      }
    })

    if (pairs.length > 0) {
      // A VALUES list parameterises cleanly through postgres.js, where an
      // array parameter with an ::int[] cast does not.
      const tuples = sql.join(
        pairs.map((pair) => sql`(${pair.executionId}::int, ${pair.tradeId}::int)`),
        sql`, `,
      )
      await tx.execute(sql`
        update executions e
        set trade_id = pair.trade_id
        from (values ${tuples}) as pair(execution_id, trade_id)
        where e.id = pair.execution_id
      `)
    }
  })

  await rollupDailyStats(accountId)
  return matched.length
}

function annotationKey(entryAt: Date, symbol: string): string {
  return `${entryAt.toISOString()}::${symbol}`
}

/**
 * Inserts fills, ignoring ones already stored.
 *
 * Idempotence comes from the unique index on (source, externalId): re-importing
 * the same export, or a broker sync that overlaps the previous window, adds
 * nothing. Rows without an external id cannot be deduplicated by the database,
 * so they are matched on their natural key instead.
 */
export async function insertExecutions(rows: NewExecution[]): Promise<number> {
  if (rows.length === 0) return 0

  const withId = rows.filter((row) => row.externalId)
  const withoutId = rows.filter((row) => !row.externalId)
  let inserted = 0

  if (withId.length > 0) {
    const result = await db
      .insert(executions)
      .values(withId)
      // The unique index is partial (WHERE external_id IS NOT NULL), and
      // Postgres only infers a partial index as the conflict arbiter when the
      // ON CONFLICT clause repeats its predicate. Without this `where`, every
      // batch insert fails with 42P10 — which would have broken the very first
      // real Tradovate sync.
      .onConflictDoNothing({
        target: [executions.source, executions.externalId],
        where: sql`external_id is not null`,
      })
      .returning({ id: executions.id })
    inserted += result.length
  }

  for (const row of withoutId) {
    // Natural key: same account, contract, side, quantity, price and instant is
    // the same fill however many times the file is uploaded.
    const existing = await db
      .select({ id: executions.id })
      .from(executions)
      .where(
        and(
          eq(executions.accountId, row.accountId),
          eq(executions.contract, row.contract),
          eq(executions.side, row.side),
          eq(executions.qty, row.qty),
          eq(executions.fillPrice, row.fillPrice),
          eq(executions.fillAt, row.fillAt as Date),
        ),
      )
      .limit(1)

    if (existing.length === 0) {
      await db.insert(executions).values(row)
      inserted += 1
    }
  }

  return inserted
}

/** Recomputes the per-day rollup an account's dashboard reads from. */
export async function rollupDailyStats(accountId: number): Promise<void> {
  const [account] = await db.select().from(accounts).where(eq(accounts.id, accountId)).limit(1)
  if (!account) return

  const rows = await db.select().from(trades).where(eq(trades.accountId, accountId))
  const series = dailySeries(rows.map(toTradeLike))

  await db.delete(dailyStats).where(eq(dailyStats.accountId, accountId))
  if (series.length === 0) return

  let equity = account.startingBalance
  const values = series.map((point) => {
    equity += point.netPnl
    const drawdownRoom =
      account.maxDrawdown && account.drawdownType === 'static'
        ? equity - (account.startingBalance - account.maxDrawdown)
        : null

    return {
      accountId,
      tradingDay: point.day,
      trades: point.trades,
      wins: point.wins,
      losses: point.losses,
      scratches: point.trades - point.wins - point.losses,
      grossPnl: point.grossPnl,
      commission: 0,
      fees: point.costs,
      netPnl: point.netPnl,
      volume: point.volume,
      equity,
      drawdownRoom,
      rSum: null,
    }
  })

  await db.insert(dailyStats).values(values)
}

export async function rebuildAllAccounts(): Promise<{ accountId: number; trades: number }[]> {
  const all = await db.select({ id: accounts.id }).from(accounts)
  const out: { accountId: number; trades: number }[] = []
  for (const account of all) {
    out.push({ accountId: account.id, trades: await rebuildTradesForAccount(account.id) })
  }
  return out
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

export type TradeFilters = {
  accountIds?: number[]
  symbols?: string[]
  from?: string
  to?: string
  direction?: 'long' | 'short'
  status?: 'open' | 'closed'
  limit?: number
  offset?: number
}

export function toTradeLike(trade: Trade): TradeLike {
  return {
    id: trade.id,
    accountId: trade.accountId,
    symbol: trade.symbol,
    direction: trade.direction,
    qty: trade.qty,
    entryAt: trade.entryAt,
    exitAt: trade.exitAt,
    tradingDay: trade.tradingDay,
    netPnl: trade.netPnl,
    grossPnl: trade.grossPnl,
    commission: trade.commission,
    fees: trade.fees,
    rMultiple: trade.rMultiple,
    riskBase: trade.riskBase,
    durationSeconds: trade.durationSeconds,
    setup: trade.setup,
    tags: trade.tags,
    mistakes: trade.mistakes,
    execScore: trade.execScore,
    status: trade.status,
  }
}

export async function listTrades(filters: TradeFilters = {}): Promise<Trade[]> {
  const conditions = []
  if (filters.accountIds?.length) conditions.push(inArray(trades.accountId, filters.accountIds))
  if (filters.symbols?.length) conditions.push(inArray(trades.symbol, filters.symbols))
  if (filters.from) conditions.push(gte(trades.tradingDay, filters.from))
  if (filters.to) conditions.push(lte(trades.tradingDay, filters.to))
  if (filters.direction) conditions.push(eq(trades.direction, filters.direction))
  if (filters.status) conditions.push(eq(trades.status, filters.status))

  return db
    .select()
    .from(trades)
    .where(conditions.length ? and(...conditions) : undefined)
    .orderBy(desc(trades.entryAt))
    .limit(filters.limit ?? 500)
    .offset(filters.offset ?? 0)
}

/**
 * Trades for analytics.
 *
 * Accounts flagged `excludeFromStats` are dropped here rather than at each call
 * site, so a demo account can never quietly inflate the headline numbers.
 */
export async function listTradesForStats(filters: TradeFilters = {}): Promise<TradeLike[]> {
  const included = await db
    .select({ id: accounts.id })
    .from(accounts)
    .where(eq(accounts.excludeFromStats, false))

  const ids = included.map((row) => row.id)
  if (ids.length === 0) return []

  const scoped = filters.accountIds?.length
    ? filters.accountIds.filter((id) => ids.includes(id))
    : ids
  if (scoped.length === 0) return []

  const rows = await listTrades({ ...filters, accountIds: scoped, limit: 20_000 })
  return rows.map(toTradeLike)
}

export async function listAccounts(): Promise<Account[]> {
  return db.select().from(accounts).orderBy(desc(accounts.status), asc(accounts.label))
}

/** Equity history per account, for the drawdown calculations. */
export async function equityHistory(): Promise<Record<number, { day: string; equity: number }[]>> {
  const rows = await db
    .select({
      accountId: dailyStats.accountId,
      day: dailyStats.tradingDay,
      equity: dailyStats.equity,
    })
    .from(dailyStats)
    .orderBy(asc(dailyStats.tradingDay))

  const out: Record<number, { day: string; equity: number }[]> = {}
  for (const row of rows) {
    ;(out[row.accountId] ??= []).push({ day: row.day, equity: row.equity })
  }
  return out
}

export async function countTrades(filters: TradeFilters = {}): Promise<number> {
  const conditions = []
  if (filters.accountIds?.length) conditions.push(inArray(trades.accountId, filters.accountIds))
  if (filters.from) conditions.push(gte(trades.tradingDay, filters.from))
  if (filters.to) conditions.push(lte(trades.tradingDay, filters.to))

  const [row] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(trades)
    .where(conditions.length ? and(...conditions) : undefined)
  return row?.count ?? 0
}

/**
 * One trade's chart, decrypted, for the authenticated route that serves it.
 *
 * Mirrors the setup version deliberately rather than sharing it: the two read
 * different tables, and a single "read a screenshot from anywhere" helper is
 * the kind of thing that later grows a caller with an unchecked id.
 */
export async function readTradeScreenshot(
  id: number,
): Promise<{ data: Buffer; type: string } | null> {
  const [row] = await db
    .select({ data: trades.screenshot, type: trades.screenshotType })
    .from(trades)
    .where(eq(trades.id, id))
    .limit(1)

  if (!row?.data) return null
  return { data: decryptBytes(Buffer.from(row.data)), type: row.type ?? 'application/octet-stream' }
}

export type CalendarTrade = {
  id: number
  netPnl: number
  /** Whether a chart is attached, so the calendar knows what it can draw. */
  hasShot: boolean
}

/**
 * Every trade's day, result and whether it has a chart — the calendar's data.
 *
 * Deliberately three columns and no more: the grid draws thumbnails for a whole
 * month at once, and pulling the notes, the model review and the screenshot
 * bytes along with them would be megabytes to render a wall of 40px pictures.
 * The images themselves are fetched one at a time by the route that serves
 * them, which is also the only place the decryption happens.
 */
export async function calendarTrades(): Promise<Map<string, CalendarTrade[]>> {
  const included = await db
    .select({ id: accounts.id })
    .from(accounts)
    .where(eq(accounts.excludeFromStats, false))
  const ids = included.map((row) => row.id)
  if (ids.length === 0) return new Map()

  const rows = await db
    .select({
      id: trades.id,
      tradingDay: trades.tradingDay,
      netPnl: trades.netPnl,
      hasShot: sql<boolean>`${trades.screenshot} is not null`,
      entryAt: trades.entryAt,
    })
    .from(trades)
    .where(inArray(trades.accountId, ids))
    .orderBy(asc(trades.entryAt))

  const byDay = new Map<string, CalendarTrade[]>()
  for (const row of rows) {
    const list = byDay.get(row.tradingDay) ?? []
    list.push({ id: row.id, netPnl: row.netPnl, hasShot: Boolean(row.hasShot) })
    byDay.set(row.tradingDay, list)
  }
  return byDay
}
