/**
 * The exact spots, not the town.
 *
 * "Chania" is not an address. Halepa and Nerokourou are forty minutes of your
 * day and €400 a month apart, and no country-level research surfaces that.
 *
 * Everything here is built for scanning rather than reading: three numbers that
 * shape a day (to the mat, to the water, to a shop), a rent range for late
 * September to December, one line on what is wrong with the street, and links
 * out to the map, to listings for your actual dates, and to the gym.
 *
 * Written for the five countries on the shortlist — Malta, Italy, Spain, Greece
 * and Cyprus. Everywhere else keeps town-level detail on its own card.
 */
import type { PlaceId } from './places'

export type Spot = {
  name: string
  /** One line. What kind of home, and who lives there. */
  what: string
  /** Furnished, per month, late September to December. */
  rent: [low: number, high: number]
  /** Minutes, and how — the three distances that shape a day. */
  mat: string
  sea: string
  shop: string
  /** Fibre at this address, in a few words. */
  net: string
  /** The one thing wrong with this street. */
  snag: string
  /** Geocodable, for maps and listing searches. */
  area: string
  /** The gym you would actually train at, for a map search. */
  gym: string
  /** Its own site, where one verifiably exists. */
  gymUrl?: string
  /** A Wikipedia title for a photograph of this specific spot. */
  wiki?: string
}

export const SPOTS: Partial<Record<PlaceId, Spot[]>> = {
  // ── Malta ─────────────────────────────────────────────────────────────────
  sliema: [
    {
      name: 'Tigné Point / The Ferries',
      what: 'Furnished 2-beds in newer blocks facing the water, lift and air conditioning.',
      rent: [1100, 1500],
      mat: '10 min walk',
      sea: '2 min — rock ledges and ladders, no sand',
      shop: '5 min to two supermarkets',
      net: 'Gigabit, Melita or GO, universal here',
      snag: 'Seafront road is loud past midnight and Tigné is a permanent building site.',
      area: 'Tigné Point, Sliema, Malta',
      gym: 'Malta Fight Co Sliema',
      gymUrl: 'https://maltafightco.com/bjj/',
      wiki: 'Sliema',
    },
    {
      name: 'Fond Għadir / Għar id-Dud',
      what: 'Older townhouse conversions behind the front, high ceilings, no lift.',
      rent: [850, 1150],
      mat: '12 min walk',
      sea: '4 min to the ledges',
      shop: '5 min to everything',
      net: 'Fibre in the street; conversions may share a line',
      snag: 'Third-floor walk-ups are normal, and stone flats are 15°C indoors in December.',
      area: 'Għar id-Dud, Sliema, Malta',
      gym: 'Malta Fight Co Sliema',
      gymUrl: 'https://maltafightco.com/bjj/',
    },
  ],
  gzira: [
    {
      name: 'Gżira seafront',
      what: 'Modern 1- and 2-beds over Msida Creek — the cheapest address near Sliema.',
      rent: [750, 1000],
      mat: '15 min walk',
      sea: '12 min to the Sliema ledges',
      shop: '5 min to Lidl',
      net: 'Gigabit fibre throughout',
      snag: 'One of the worst traffic roads on the island, directly outside.',
      area: 'Gżira, Malta',
      gym: 'Malta Fight Co Sliema',
      gymUrl: 'https://maltafightco.com/bjj/',
      wiki: 'Gżira',
    },
  ],
  mellieha: [
    {
      name: 'Mellieħa town',
      what: '3-bed maisonettes with a roof terrace — a whole house, affordably, in Malta.',
      rent: [850, 1200],
      mat: '35–45 min drive — the whole objection',
      sea: '10 min downhill to Għadira sand',
      shop: '2 min to the square',
      net: 'Fibre in the town',
      snag: 'Everything is a hill, and the bus to Valletta takes 50 minutes.',
      area: 'Mellieħa, Malta',
      gym: 'Malta Fight Co Sliema',
      gymUrl: 'https://maltafightco.com/bjj/',
      wiki: 'Mellieħa',
    },
  ],
  gozo: [
    {
      name: 'Marsalforn & Xlendi',
      what: 'Converted farmhouses with a private pool and courtyard.',
      rent: [700, 1000],
      mat: 'Ferry + 45 min — every session',
      sea: '2 min to swim off rock; Ramla sand 15 min',
      shop: '10 min to Victoria',
      net: 'Fibre in both towns, not outlying farmhouses',
      snag: 'A third of Marsalforn open by December, and the last ferry shapes your evenings.',
      area: 'Marsalforn, Gozo, Malta',
      gym: 'Victoria Gozo fitness',
      wiki: 'Marsalforn',
    },
  ],

  // ── Italy ─────────────────────────────────────────────────────────────────
  'aci-castello': [
    {
      name: 'Aci Trezza',
      what: 'Fishing-village flats above the harbour, most with a terrace.',
      rent: [550, 800],
      mat: '15 min drive to Catania',
      sea: '3 min — swim off lava rock',
      shop: '5 min to a Conad',
      net: 'FTTH on the coast road — insist on FTTH, not FTTC',
      snag: 'You need a car, and the village is quiet from November.',
      area: 'Aci Trezza, Catania, Italy',
      gym: 'Fundamental BJJ Catania',
      wiki: 'Aci Trezza',
    },
    {
      name: 'Catania — Corso Italia',
      what: 'Large flats in 20th-century blocks, the residential city rather than the tourist one.',
      rent: [600, 850],
      mat: '10–15 min walk to two academies',
      sea: '15 min to La Playa sand',
      shop: '5 min, and the fish market you came for',
      net: 'Best fibre in eastern Sicily',
      snag: 'A working port city — noisy, hard parking, Etna ash on the cars.',
      area: 'Corso Italia, Catania, Italy',
      gym: 'BJJ Catania Lavica Project',
      wiki: 'Catania',
    },
  ],
  mondello: [
    {
      name: 'Mondello — Valdesi',
      what: 'Villas and villa flats behind the bay, mostly summer houses let cheap off-season.',
      rent: [600, 900],
      mat: '20 min into Palermo',
      sea: '2 min to the best swimming bay in Sicily',
      shop: '5 min; the big ones are on the Palermo road',
      net: 'Fibre in built-up Mondello, not the back villas',
      snag: 'A summer suburb — very quiet by November.',
      area: 'Mondello, Palermo, Italy',
      gym: 'BJJ Palermo Sicilia',
      wiki: 'Mondello',
    },
  ],
  monopoli: [
    {
      name: 'Monopoli centro storico',
      what: 'Restored stone flats inside the walls, thick walls, roof terraces.',
      rent: [650, 900],
      mat: '40 min drive or 45 min train to Bari',
      sea: '1 min — Cala Porta Vecchia is inside the old town',
      shop: '5 min outside the walls',
      net: 'FTTH in the centre',
      snag: 'No parking, and stone houses at 14°C on electric heating are expensive.',
      area: 'Centro Storico, Monopoli, Italy',
      gym: 'WCRA Bari Centro BJJ',
      wiki: 'Monopoli',
    },
    {
      name: 'Polignano a Mare — the plateau',
      what: 'Newer flats above the cliffs with balconies and easy parking.',
      rent: [600, 850],
      mat: '35 min to Bari',
      sea: '5 min to Lama Monachile',
      shop: '5 min on foot',
      net: 'FTTH on the plateau',
      snag: 'A day-trip town that empties completely after October.',
      area: 'Polignano a Mare, Italy',
      gym: 'WCRA Bari Centro BJJ',
      wiki: 'Polignano a Mare',
    },
  ],
  lecce: [
    {
      name: 'Lecce — Mazzini',
      what: 'Big student-city flats in the newer quarters.',
      rent: [450, 700],
      mat: 'University clubs only, no real MMA',
      sea: '20 min drive to San Cataldo, closed in winter',
      shop: 'Everything on foot',
      net: 'FTTH across the city',
      snag: 'It is 25 minutes from the sea — inland Salento defeats the point.',
      area: 'Lecce, Italy',
      gym: 'BJJ Lecce Salento',
      wiki: 'Lecce',
    },
  ],
  cagliari: [
    {
      name: 'Poetto — Quartu end',
      what: 'Flats on the beach road, balconies over the water.',
      rent: [600, 900],
      mat: '15 min drive into the city',
      sea: 'Across the road — 8 km of sand to run',
      shop: '5 min on Viale Marconi',
      net: 'Fibre along the Poetto road',
      snag: 'The mistral makes the front cold from November and the kiosks shut.',
      area: 'Poetto, Cagliari, Italy',
      gym: 'CL Fight Team Cagliari',
      gymUrl: 'https://mmacagliari.it/',
      wiki: 'Poetto',
    },
    {
      name: 'Cagliari — Villanova',
      what: 'Old-city flats near the market and port, high ceilings, no lift.',
      rent: [550, 800],
      mat: '10 min walk',
      sea: '15 min by bus to Poetto',
      shop: '10 min to San Benedetto, Italy’s largest covered market',
      net: 'FTTH, 1 Gbps for €25–35',
      snag: 'Steep streets, and the same December heating problem.',
      area: 'Villanova, Cagliari, Italy',
      gym: 'Wolfpack Fighting Club Cagliari',
      gymUrl: 'https://www.wolfpackfightingclub.com/',
      wiki: 'Cagliari',
    },
  ],
  sanremo: [
    {
      name: 'Sanremo seafront',
      what: 'Flats along the Corso Imperatrice with a sea view.',
      rent: [700, 1100],
      mat: 'Club level only; Nice is an hour',
      sea: 'Across the road, pebble',
      shop: 'Everything in town',
      net: 'FTTH, reliable',
      snag: '12°C in December and grey — a northern winter with palm trees.',
      area: 'Sanremo, Italy',
      gym: 'Sanremo boxe e MMA',
      wiki: 'Sanremo',
    },
  ],

  // ── Spain ─────────────────────────────────────────────────────────────────
  valencia: [
    {
      name: 'Ruzafa',
      what: 'Restored 19th-century flats, high ceilings, in the neighbourhood everyone wants.',
      rent: [900, 1300],
      mat: '10 min walk or bike to two academies',
      sea: '20 min by bike down the Turia park',
      shop: 'Mercado de Ruzafa on the doorstep',
      net: 'Gigabit symmetric, €30, four providers',
      snag: 'It is the bar district — street noise past 02:00 Thursday to Sunday.',
      area: 'Ruzafa, Valencia, Spain',
      gym: 'Michal Adamczak BJJ Academy Valencia',
      wiki: 'Russafa',
    },
    {
      name: 'El Cabanyal / Patacona',
      what: 'Restored fisherman’s houses in the old maritime quarter, or newer flats in Patacona.',
      rent: [800, 1200],
      mat: '15 min by bike into the city',
      sea: '2–5 min on foot to wide sand',
      shop: 'Mercado del Cabanyal; Mercadona 5 min',
      net: 'Full FTTH',
      snag: 'Half restored, half not — the difference is one block. Walk it first.',
      area: 'El Cabanyal, Valencia, Spain',
      gym: 'S.H.O.O.T. MMA Valencia',
      wiki: 'El Cabanyal',
    },
  ],
  malaga: [
    {
      name: 'Málaga — Soho',
      what: 'Flats in the regenerated port quarter, walkable to everything.',
      rent: [1000, 1400],
      mat: '10 min to Rilion Gracie; 20 min train to Scramble',
      sea: '10 min walk to Malagueta',
      shop: '5 min to Atarazanas market',
      net: 'Full FTTH',
      snag: 'Priced for short lets — rent goes up for December, not down.',
      area: 'Soho, Málaga, Spain',
      gym: 'Rilion Gracie Málaga',
      wiki: 'Málaga',
    },
    {
      name: 'Torremolinos — La Carihuela',
      what: 'Old fishing-quarter flats and small townhouses on the promenade.',
      rent: [700, 1000],
      mat: '10 min walk to Scramble Academy',
      sea: 'On the promenade — 7 km to run',
      shop: '2 min along the front',
      net: 'Gigabit FTTH, €30',
      snag: 'The strip 400 m inland is package-holiday Britain.',
      area: 'La Carihuela, Torremolinos, Spain',
      gym: 'Scramble Academy Torremolinos',
      wiki: 'Torremolinos',
    },
  ],
  alicante: [
    {
      name: 'Playa de San Juan',
      what: 'Modern flats a street back from 7 km of sand, tram into the city.',
      rent: [700, 1000],
      mat: '15 min tram to Fightzone — 100+ classes a week',
      sea: '2–5 min on foot',
      shop: '5 min in the neighbourhood',
      net: 'Gigabit FTTH everywhere',
      snag: 'A summer suburb — quiet after 20:00 from November.',
      area: 'Playa de San Juan, Alicante, Spain',
      gym: 'Fightzone Costa Blanca',
      wiki: 'Playa de San Juan',
    },
    {
      name: 'Alicante — Mercado',
      what: 'City flats by the market with Postiguet beach at the end of the street.',
      rent: [650, 950],
      mat: '15 min tram to Fightzone',
      sea: '10 min walk to Postiguet',
      shop: '5 min to Mercado Central',
      net: 'Gigabit FTTH, €30',
      snag: 'Duller than Valencia at every hour that is not training.',
      area: 'Mercado Central, Alicante, Spain',
      gym: 'Climent Club Alicante',
      wiki: 'Alicante',
    },
  ],
  marbella: [
    {
      name: 'Nueva Andalucía',
      what: 'Flats in gated complexes with a pool and parking — the normal rental here.',
      rent: [1300, 1900],
      mat: '10–15 min drive',
      sea: '5–10 min; 16°C in January',
      shop: 'Everything, priced for the market',
      net: 'Gigabit FTTH',
      snag: 'Dearer than Valencia and Málaga, and you drive everywhere.',
      area: 'Nueva Andalucía, Marbella, Spain',
      gym: 'Patrick Bittan Academy Marbella',
      wiki: 'Marbella',
    },
  ],
  palma: [
    {
      name: 'Santa Catalina',
      what: 'The good Palma neighbourhood — market, bars, walkable.',
      rent: [900, 1300],
      mat: '10 min to SurUnion or BJJPalma',
      sea: '10 min by bus to Cala Major',
      shop: 'Mercat de Santa Catalina on the doorstep',
      net: 'Gigabit FTTH',
      snag: 'The island outside Palma closes from November.',
      area: 'Santa Catalina, Palma, Spain',
      gym: 'SurUnion BJJ Palma',
      wiki: 'Palma de Mallorca',
    },
  ],
  'las-palmas': [
    {
      name: 'Las Canteras — La Puntilla',
      what: 'Flats a street back from the beach, in a real city rather than a resort.',
      rent: [900, 1300],
      mat: '10 min to Team Romero',
      sea: '1–3 min — swimmable every month of the year',
      shop: '10 min to Mercado del Puerto',
      net: 'Gigabit; the Atlantic cables land here',
      snag: 'Your months are high season, so you pay more and it is busy.',
      area: 'Las Canteras, Las Palmas, Spain',
      gym: 'Team Romero BJJ Las Palmas',
      wiki: 'Las Canteras Beach',
    },
  ],
  'costa-adeje': [
    {
      name: 'La Caleta',
      what: 'A quiet village at the end of the Adeje strip, flats and townhouses.',
      rent: [900, 1300],
      mat: '70 min north to Santa Cruz for a real room',
      sea: '5 min — 22°C in December',
      shop: '5 min uphill in Adeje',
      net: 'Fibre through the strip',
      snag: 'A resort with residents attached, at peak-season prices.',
      area: 'La Caleta, Adeje, Tenerife, Spain',
      gym: 'BJJ Tenerife Sur Adeje',
      wiki: 'Adeje',
    },
  ],

  // ── Greece ────────────────────────────────────────────────────────────────
  chania: [
    {
      name: 'Halepa',
      what: 'Neoclassical houses and 1970s flats east of the old town, balconies, sea views.',
      rent: [500, 750],
      mat: '10 min walk to Chania Combat Sports',
      sea: '15 min walk to Nea Chora',
      shop: '10 min; covered market 15',
      net: 'Cosmote FTTH — check the street number',
      snag: 'It is a hill, and old stone flats are cold and damp in December.',
      area: 'Halepa, Chania, Greece',
      gym: 'Chania Combat Sports',
      wiki: 'Chania',
    },
    {
      name: 'Akrotiri — Kounoupidiana',
      what: 'Detached houses with gardens and sea views. The house you actually wanted.',
      rent: [700, 1100],
      mat: '12 min drive — not walkable',
      sea: '5–10 min to Kalathas, Stavros, Tersanas',
      shop: 'Full supermarket in the village; university keeps it awake',
      net: 'FTTH here; VDSL further out towards Stavros',
      snag: 'You need a car, and the beaches are empty from November.',
      area: 'Kounoupidiana, Akrotiri, Chania, Greece',
      gym: 'Chania Combat Sports',
      wiki: 'Akrotiri, Chania',
    },
  ],
  rethymno: [
    {
      name: 'Rethymno — Kastella',
      what: 'Venetian-era flats behind the beach, walkable to everything.',
      rent: [400, 650],
      mat: '1 hr drive to Chania for MMA',
      sea: 'End of the street — 12 km of sand',
      shop: '10 min; Thursday market',
      net: 'Cosmote FTTH in the old town',
      snag: 'Low training ceiling, and February is genuinely quiet.',
      area: 'Rethymno, Crete, Greece',
      gym: 'Rethymno BJJ Crete',
      wiki: 'Rethymno',
    },
  ],
  heraklion: [
    {
      name: 'Ammoudara',
      what: 'Flats along the beach strip 10 minutes west of the city.',
      rent: [450, 700],
      mat: '10–15 min into the city — biggest scene on Crete',
      sea: 'Across the road, flat promenade to run',
      shop: 'Full supermarkets on the strip',
      net: 'Best fibre on the island, two providers',
      snag: 'A package-holiday strip, and bleak in December.',
      area: 'Ammoudara, Heraklion, Greece',
      gym: 'Heraklion BJJ MMA',
      wiki: 'Heraklion',
    },
  ],
  'athens-riviera': [
    {
      name: 'Ano Glyfada',
      what: 'Good flats a few streets above the shopping district, quieter and cheaper.',
      rent: [900, 1400],
      mat: '10–15 min to Alliance or Kimura — real fundamentals programmes',
      sea: '10 min walk; tram along the coast',
      shop: 'Everything, all year',
      net: 'Full gigabit, multiple providers',
      snag: '€900–1,400 is roughly double Chania for the same flat.',
      area: 'Glyfada, Athens, Greece',
      gym: 'Alliance Jiu Jitsu Athens',
      wiki: 'Glyfada',
    },
  ],
  kalamata: [
    {
      name: 'Kalamata — Navarinou',
      what: 'Flats along the front with balconies over the bay.',
      rent: [400, 650],
      mat: '10 min to The Camp 10',
      sea: 'Across the road; sand 20–40 min west',
      shop: 'Producer-direct market — cheapest good food in Greece',
      net: 'FTTH along the front',
      snag: 'Small, and everything routes through Athens.',
      area: 'Navarinou, Kalamata, Greece',
      gym: 'The Camp 10 Kalamata',
      wiki: 'Kalamata',
    },
  ],
  rhodes: [
    {
      name: 'Rhodes new town — Zefyros',
      what: 'Year-round residential flats, unlike the resort strips.',
      rent: [400, 650],
      mat: '10 min south to Rhodes Knights BJJ',
      sea: 'Two coasts within 10 min; warmest sea in Greece',
      shop: 'Full supermarkets and a market',
      net: 'FTTH in town and Ialysos',
      snag: 'The island shuts hard in November — the town does not.',
      area: 'Zefyros, Rhodes, Greece',
      gym: 'Rhodes Knights BJJ',
      wiki: 'Rhodes (city)',
    },
  ],
  thessaloniki: [
    {
      name: 'Kalamaria',
      what: 'Seafront-adjacent flats in the good residential district.',
      rent: [350, 550],
      mat: '10 min — strongest scene outside Athens',
      sea: 'None. Halkidiki is 60–90 min and closed',
      shop: 'Best food city in Greece, and the cheapest',
      net: 'Full fibre, two providers',
      snag: '10°C and grey in December, with no sea.',
      area: 'Kalamaria, Thessaloniki, Greece',
      gym: 'MMA Klub Thessaloniki',
      wiki: 'Kalamaria',
    },
  ],
  corfu: [
    {
      name: 'Corfu Town — Garitsa',
      what: 'Venetian flats on the bay, and stone houses with gardens just outside.',
      rent: [400, 700],
      mat: '5 min to Cloud9 BJJ — the only Machado academy in Europe',
      sea: '10 min to Mon Repos',
      shop: 'Full market and supermarkets',
      net: 'Fibre in town and the coast road',
      snag: '14 rain days in November, 15 in December — the wettest place in Greece.',
      area: 'Garitsa, Corfu, Greece',
      gym: 'Cloud9 BJJ Corfu',
      wiki: 'Corfu (city)',
    },
  ],

  // ── Cyprus ────────────────────────────────────────────────────────────────
  limassol: [
    {
      name: 'Potamos Germasogeias',
      what: 'Modern 2-beds between the strip and the sea, most with a pool in the block.',
      rent: [1100, 1600],
      mat: '5–10 min to Checkmat or Gracie Barra, taught in English',
      sea: 'Across the road; 24°C in November',
      shop: '5 min, including Middle Eastern staples',
      net: 'Cyta gigabit — most reliable on this list',
      snag: 'A finance-and-tourism suburb, not a town, at twice Chania’s rent.',
      area: 'Potamos Germasogeias, Limassol, Cyprus',
      gym: 'Checkmat Limassol',
      wiki: 'Limassol',
    },
  ],
  paphos: [
    {
      name: 'Coral Bay / Peyia',
      what: 'Villas with private pools — genuinely normal to rent here.',
      rent: [800, 1300],
      mat: '15 min drive to Furious Fighters or Kings BJJ',
      sea: '5 min — warmest winter sea in the EU',
      shop: '5 min in Peyia; full ones in Paphos',
      net: 'Fibre through the coastal strip',
      snag: 'You need a car, and the resident population skews retired British.',
      area: 'Coral Bay, Peyia, Cyprus',
      gym: 'Furious Fighters Paphos',
      gymUrl: 'https://furiousfighterscy.com/',
      wiki: 'Coral Bay, Cyprus',
    },
  ],
  larnaca: [
    {
      name: 'Mackenzie',
      what: 'Flats on the Mackenzie beach strip, or houses inland at Oroklini.',
      rent: [650, 1000],
      mat: '45 min drive to Limassol, realistically',
      sea: 'On the strip; better sand 20 min north',
      shop: 'Everything, cheaper than Limassol',
      net: 'Cyta gigabit FTTH',
      snag: 'It is the airport town — convenient, and not a reason to be anywhere.',
      area: 'Mackenzie Beach, Larnaca, Cyprus',
      gym: 'Cyprus Top Team Larnaca',
      wiki: 'Larnaca',
    },
  ],
  protaras: [
    {
      name: 'Pernera',
      what: 'Villas priced for summer, let cheap on a winter contract.',
      rent: [600, 1000],
      mat: '45 min to Larnaca, 70 to Limassol',
      sea: 'Walkable to Fig Tree Bay — best water on the island',
      shop: 'Two supermarkets stay open; the strip does not',
      net: 'Fibre in the resort strip',
      snag: 'Four in five businesses close from November.',
      area: 'Pernera, Protaras, Cyprus',
      gym: 'Cyprus Top Team Larnaca',
      wiki: 'Protaras',
    },
  ],
  nicosia: [
    {
      name: 'Engomi',
      what: 'The cheapest housing on the island, in a real working city.',
      rent: [550, 850],
      mat: '10 min — several academies',
      sea: 'None. 45 min in any direction',
      shop: 'Best supply and lowest prices in Cyprus',
      net: 'Cyta gigabit FTTH',
      snag: 'Choosing an island and living inland on it defeats the exercise.',
      area: 'Engomi, Nicosia, Cyprus',
      gym: 'Nicosia BJJ Cyprus',
      wiki: 'Nicosia',
    },
  ],
  // ── Portugal ──────────────────────────────────────────────────────────────
  cascais: [
    {
      name: 'Cascais — Monte Estoril',
      what: 'Flats between the town and Estoril, on the train line into Lisbon.',
      rent: [1300, 1900],
      mat: '10 min to Flow MMA — small classes, built for beginners',
      sea: '5 min to Tamariz; the Atlantic is 17–19°C',
      shop: '5 min to a Pingo Doce',
      net: 'Gigabit FTTH, among the best networks in the EU',
      snag: 'The sea never warms, and IFICI excludes remote work for foreign clients.',
      area: 'Monte Estoril, Cascais, Portugal',
      gym: 'Flow MMA Cascais',
      wiki: 'Cascais',
    },
  ],
  carcavelos: [
    {
      name: 'Parede',
      what: 'Commuter-belt flats a street back from the rock pools, cheaper than Cascais.',
      rent: [1000, 1500],
      mat: '20 min by train to Gracie Barra Campolide',
      sea: '5 min to Carcavelos sand',
      shop: '5 min to a Pingo Doce',
      net: 'Gigabit FTTH',
      snag: 'A commuter suburb — the least interesting address on this coast.',
      area: 'Parede, Cascais, Portugal',
      gym: 'Gracie Barra Campolide Lisbon',
      wiki: 'Parede',
    },
  ],
  'lagos-pt': [
    {
      name: 'Lagos — Meia Praia end',
      what: 'Flats and small townhouses behind 4 km of sand, let cheap out of season.',
      rent: [900, 1400],
      mat: '5 min to Shinobi Academy or Rey BJJ',
      sea: '3 min to Meia Praia',
      shop: '10 min to the market',
      net: 'Fibre in the town',
      snag: 'Half the town closes in November and the sea is 19°C.',
      area: 'Meia Praia, Lagos, Portugal',
      gym: 'Shinobi Academy Lagos',
      wiki: 'Lagos, Portugal',
    },
  ],
  portimao: [
    {
      name: 'Praia da Rocha',
      what: 'The cheapest real housing on the Algarve coast, in a working town.',
      rent: [700, 1100],
      mat: '25 min to Lagos; no MMA in the Algarve at all',
      sea: '2 min to a wide sheltered beach',
      shop: '10 min to the market and a working fishing port',
      net: 'Fibre in the town, 1 Gbps',
      snag: 'A working town with a resort strip bolted on; not the brochure Algarve.',
      area: 'Praia da Rocha, Portimão, Portugal',
      gym: 'Rey BJJ Lagos',
      wiki: 'Praia da Rocha',
    },
  ],
  ericeira: [
    {
      name: 'Ericeira town',
      what: 'Houses near the coast road in a surf village of 7,000.',
      rent: [1000, 1500],
      mat: '45 min to Lisbon; nothing local',
      sea: '2 min — world-class waves, rarely a swimming beach',
      shop: '5 min; small-town Portuguese',
      net: 'Fibre in the town',
      snag: '13 rain days in November, and if you do not surf there is no reason to be here.',
      area: 'Ericeira, Portugal',
      gym: 'Gracie Barra Campolide Lisbon',
      wiki: 'Ericeira',
    },
  ],
  funchal: [
    {
      name: 'Funchal — Lido',
      what: 'Flats on the hillside with sea views, walking distance to the promenade.',
      rent: [800, 1300],
      mat: 'Local BJJ clubs; nothing serious without a flight',
      sea: '5 min to a lido — no sand anywhere on the island',
      shop: '10 min to Mercado dos Lavradores',
      net: 'Gigabit FTTH, and a large remote-work population testing it',
      snag: 'Every road is a 10% gradient, and December is its high season.',
      area: 'Lido, Funchal, Madeira, Portugal',
      gym: 'BJJ Madeira Funchal',
      wiki: 'Funchal',
    },
  ],

  // ── Croatia ───────────────────────────────────────────────────────────────
  split: [
    {
      name: 'Bačvice / Firule',
      what: 'Flats behind the city beach, walkable to the old town.',
      rent: [700, 1100],
      mat: '10 min to Mizfits BJJ — two mat halls and a cage',
      sea: '3 min to Bačvice; Kašjuni under the pines is 15',
      shop: '5 min to the green market',
      net: 'FTTH in the city',
      snag: '11°C in December with the bura, and the ferries drop to a skeleton timetable.',
      area: 'Bačvice, Split, Croatia',
      gym: 'Mizfits BJJ Split',
      gymUrl: 'https://mizfitsbjjsplit.com/en/mizfits-bjj-academy-split/',
      wiki: 'Split, Croatia',
    },
  ],
  zadar: [
    {
      name: 'Zadar — Kolovare',
      what: 'Flats along the town beach, 10 minutes from the peninsula.',
      rent: [500, 900],
      mat: '10 min to Checkmat Zadar — grappling, no MMA',
      sea: 'Across the road',
      shop: '10 min to the market',
      net: 'FTTH',
      snag: 'Same cold Adriatic winter as Split with less to do in it.',
      area: 'Kolovare, Zadar, Croatia',
      gym: 'Checkmat Zadar',
      wiki: 'Zadar',
    },
  ],
  sibenik: [
    {
      name: 'Šibenik old town',
      what: 'Stone flats in the cheapest coastal town in Croatia that is still a real town.',
      rent: [400, 800],
      mat: '45 min to Split — nothing local',
      sea: '15 min to Solaris',
      shop: '5 min',
      net: 'FTTH in the centre',
      snag: 'A quiet stone town at 11°C in December, with no mat.',
      area: 'Šibenik, Croatia',
      gym: 'Mizfits BJJ Split',
      wiki: 'Šibenik',
    },
  ],
  opatija: [
    {
      name: 'Rijeka — Pećine',
      what: 'Flats on the coast road in a working port city rather than the resort.',
      rent: [500, 900],
      mat: '10 min — Rijeka has real clubs, Opatija does not',
      sea: 'Swimming platforms along the Lungomare',
      shop: '10 min',
      net: 'FTTH',
      snag: 'The wettest corner of Croatia — 13 rain days in November.',
      area: 'Pećine, Rijeka, Croatia',
      gym: 'BJJ Klub Rijeka',
      wiki: 'Rijeka',
    },
  ],
  dubrovnik: [
    {
      name: 'Lapad',
      what: 'The residential peninsula west of the old town, quieter and cheaper.',
      rent: [700, 1300],
      mat: 'Essentially nothing; Split is three hours',
      sea: '5 min to the Lapad coves',
      shop: '10 min',
      net: 'FTTH',
      snag: 'Landlords would rather rent nightly, and December is a near-empty town.',
      area: 'Lapad, Dubrovnik, Croatia',
      gym: 'Mizfits BJJ Split',
      wiki: 'Lapad',
    },
  ],

  // ── Montenegro ────────────────────────────────────────────────────────────
  budva: [
    {
      name: 'Bečići',
      what: 'Flats and small houses behind a 2 km beach, 10 minutes from Budva.',
      rent: [400, 800],
      mat: '10 min to MMA Klub Budva at the sports centre',
      sea: '3 min to sand',
      shop: '5 min',
      net: 'Fibre, adequate rather than good — test it in the flat',
      snag: 'The strip is boarded up from November and Montenegro is outside the EU.',
      area: 'Bečići, Budva, Montenegro',
      gym: 'MMA Klub Budva',
      wiki: 'Bečići',
    },
  ],
  tivat: [
    {
      name: 'Donja Lastva',
      what: 'Flats a walk from Porto Montenegro without the marina price.',
      rent: [600, 1100],
      mat: '20 min to Budva',
      sea: 'Bay water — calm, warm, not a swimming beach',
      shop: '5 min',
      net: 'Fibre around the marina',
      snag: '14 rain days in November and December alike.',
      area: 'Donja Lastva, Tivat, Montenegro',
      gym: 'MMA Klub Budva',
      wiki: 'Tivat',
    },
  ],
  'herceg-novi': [
    {
      name: 'Savina',
      what: 'Stone houses and flats above the promenade, sea views the whole way.',
      rent: [350, 700],
      mat: '40 min to Dubrovnik; nothing local',
      sea: '5 min — 7 km of swimming platforms',
      shop: '10 min',
      net: 'Fibre in the town',
      snag: 'One of the rainiest towns on the Adriatic, and everything is stairs.',
      area: 'Savina, Herceg Novi, Montenegro',
      gym: 'PitBull BJJ Podgorica',
      wiki: 'Herceg Novi',
    },
  ],
  bar: [
    {
      name: 'Bar — Šušanj',
      what: 'The cheapest coastal rent in Europe that is still a functioning town.',
      rent: [250, 550],
      mat: '45 min to Podgorica — nothing on the coast',
      sea: '5 min to pebble; Ulcinj sand is 30 min',
      shop: '5 min to the cheapest market on the Adriatic',
      net: 'Fibre in the centre',
      snag: 'A container port chosen on price, with no scene of any kind.',
      area: 'Šušanj, Bar, Montenegro',
      gym: 'PitBull BJJ Podgorica',
      wiki: 'Bar, Montenegro',
    },
  ],

  // ── Albania ───────────────────────────────────────────────────────────────
  vlore: [
    {
      name: 'Vlorë — Lungomare',
      what: 'New-build flats on the front, most with a balcony over the bay.',
      rent: [250, 550],
      mat: '1 hr south to Sarandë for the only club on the coast',
      sea: '2 min; the clear water is 20 min south at Radhimë',
      shop: '5 min — exceptional produce, almost free',
      net: 'Fibre, and better than its reputation — built late, built new',
      snag: 'Construction everywhere and chaotic driving.',
      area: 'Lungomare, Vlorë, Albania',
      gym: 'HISTORIA jiu jitsu Sarandë',
      wiki: 'Vlorë',
    },
  ],
  sarande: [
    {
      name: 'Sarandë front / Ksamil',
      what: 'Sea-view flats in town, or houses at Ksamil 15 minutes south.',
      rent: [250, 600],
      mat: '5 min to HISTORIA — the only mat on the Albanian coast',
      sea: '2 min in town; Ksamil is the best water in Albania',
      shop: '5 min',
      net: 'Fibre in the town',
      snag: 'Closes almost entirely from November — restaurants, shops, transport.',
      area: 'Sarandë, Albania',
      gym: 'HISTORIA jiu jitsu Sarandë',
      wiki: 'Sarandë',
    },
  ],
  golem: [
    {
      name: 'Golem',
      what: 'Cheap new flats behind a long shallow beach, 30 min from Tirana airport.',
      rent: [200, 500],
      mat: '40 min to Tirana, which has the country’s gyms',
      sea: '3 min, and murky in summer',
      shop: '5 min — the main agricultural region',
      net: 'Fibre',
      snag: 'The Durrës–Tirana road is one of the worst traffic corridors in the Balkans.',
      area: 'Golem, Durrës, Albania',
      gym: 'BJJ Tirana Albania',
      wiki: 'Golem, Albania',
    },
  ],
  himare: [
    {
      name: 'Himarë / Livadhi',
      what: 'Houses with terraces over the sea on the best coast in the country.',
      rent: [300, 700],
      mat: 'Nothing within 90 minutes',
      sea: '2 min to Livadhi; Jala and Dhërmi are 15',
      shop: 'Village shops only',
      net: 'Fibre in the town, not the coves',
      snag: 'A village on a mountain road, closed from November, with a health centre not a hospital.',
      area: 'Himarë, Albania',
      gym: 'HISTORIA jiu jitsu Sarandë',
      wiki: 'Himarë',
    },
  ],

  // ── Bulgaria ──────────────────────────────────────────────────────────────
  varna: [
    {
      name: 'Briz / Sea Garden',
      what: 'Good flats above the Sea Garden, walkable to the centre.',
      rent: [350, 650],
      mat: '10 min to House of Jiu-Jitsu Varna',
      sea: '5 min; unswimmable from October',
      shop: '5 min — best value market food in the EU',
      net: 'Gigabit for €15, among the fastest in Europe',
      snag: '8°C in December and a coast that shuts completely.',
      area: 'Briz, Varna, Bulgaria',
      gym: 'House of Jiu-Jitsu Varna',
      wiki: 'Varna, Bulgaria',
    },
  ],
  burgas: [
    {
      name: 'Burgas — Sarafovo',
      what: 'Flats and small houses by the sea, 10 minutes from the centre.',
      rent: [250, 550],
      mat: '10 min to Bulgarian Bulls BJJ or GFTeam',
      sea: '3 min, and finished by October',
      shop: '5 min',
      net: 'Gigabit fibre',
      snag: 'Industrial, flat, and the coast closes in October.',
      area: 'Sarafovo, Burgas, Bulgaria',
      gym: 'GFTeam Burgas',
      wiki: 'Burgas',
    },
  ],
  sozopol: [
    {
      name: 'Sozopol old town',
      what: 'Stone houses on a walled peninsula, let for almost nothing out of season.',
      rent: [250, 600],
      mat: '30 min to Burgas — nothing here',
      sea: '1 min to the best water on the Bulgarian coast',
      shop: 'Two shops open in winter; the rest is Burgas',
      net: 'Fibre in the town',
      snag: 'A town of 5,000 that in December is a stone village in the wind.',
      area: 'Sozopol, Bulgaria',
      gym: 'GFTeam Burgas',
      wiki: 'Sozopol',
    },
  ],
  sofia: [
    {
      name: 'Lozenets',
      what: 'The good central district, walkable, with Vitosha behind it.',
      rent: [450, 850],
      mat: '10 min to Champions Academy Bulgaria',
      sea: 'None. Vitosha mountain is 20 min',
      shop: 'Best supply in the country, still cheap',
      net: 'Gigabit fibre for €15–20',
      snag: 'Landlocked, cold, and winter air quality regularly breaches EU limits.',
      area: 'Lozenets, Sofia, Bulgaria',
      gym: 'Champions Academy Sofia',
      wiki: 'Lozenets, Sofia',
    },
  ],

  // ── Poland ────────────────────────────────────────────────────────────────
  sopot: [
    {
      name: 'Sopot / Wrzeszcz',
      what: 'Flats in the spa town or the good Gdańsk district, on the SKM line.',
      rent: [500, 900],
      mat: '15 min to Akademia Sarmatia — fixed-start beginner courses',
      sea: '5 min to white sand and pine forest; the Baltic is 6°C',
      shop: '5 min',
      net: 'Gigabit for €12–20 — best value on this list',
      snag: '3°C in December, dark by 15:30, and the seafront is dead from October.',
      area: 'Sopot, Poland',
      gym: 'Akademia Sarmatia Gdańsk',
      wiki: 'Sopot',
    },
  ],
  gdynia: [
    {
      name: 'Gdynia — Orłowo',
      what: 'Flats by the cliff and the pier, cheaper than Sopot for the same coast.',
      rent: [450, 800],
      mat: '20 min by train to Sarmatia',
      sea: '5 min',
      shop: '5 min',
      net: 'Gigabit fibre',
      snag: 'The same Baltic winter with less of a town to spend it in.',
      area: 'Orłowo, Gdynia, Poland',
      gym: 'Akademia Sarmatia Gdańsk',
      wiki: 'Orłowo',
    },
  ],
  krakow: [
    {
      name: 'Kazimierz / Podgórze',
      what: 'Flats in the old Jewish quarter and across the river, both walkable.',
      rent: [450, 850],
      mat: '10 min — 16 BJJ gyms in the city, several with term-start beginner courses',
      sea: 'None. The Tatras are two hours',
      shop: 'Very good markets, very cheap',
      net: 'Gigabit fibre',
      snag: 'Winter smog regularly breaches EU particulate limits from November.',
      area: 'Kazimierz, Kraków, Poland',
      gym: 'MMA Academy Kraków',
      wiki: 'Kazimierz',
    },
  ],
  warsaw: [
    {
      name: 'Mokotów',
      what: 'The good residential district, parks, walkable, well connected.',
      rent: [650, 1100],
      mat: '10 min to Atos Warsaw or Akademia Gorila',
      sea: 'A river beach on the Vistula, and that is it',
      shop: 'Everything, cheap for a capital',
      net: 'Gigabit fibre',
      snag: 'A landlocked capital at 52° north — 2°C in December.',
      area: 'Mokotów, Warsaw, Poland',
      gym: 'Atos Jiu Jitsu Warsaw',
      wiki: 'Mokotów',
    },
  ],

  // ── Georgia ───────────────────────────────────────────────────────────────
  batumi: [
    {
      name: 'Batumi — Old Boulevard',
      what: 'Sea-view flats in new towers, let for very little out of season.',
      rent: [250, 600],
      mat: '10 min to Batumi Boxing Academy; the BJJ is in Tbilisi',
      sea: '2 min to pebble; done by October',
      shop: '5 min — Georgian food is the reason to come',
      net: 'Fibre, cheap, stress-tested by a big remote-work population',
      snag: 'Over 2,000 mm of rain a year, and 13 rain days in each of Nov and Dec.',
      area: 'Old Boulevard, Batumi, Georgia',
      gym: 'Batumi Boxing Academy',
      wiki: 'Batumi',
    },
  ],
  tbilisi: [
    {
      name: 'Vake',
      what: 'The good district — park, cafés, walkable, full of foreigners.',
      rent: [350, 750],
      mat: '10 min to Warriors or Legion BJJ',
      sea: 'None. The Caucasus is 90 min',
      shop: 'Dezerter Bazaar — best food per euro on this list',
      net: 'Fibre, €15–25, reliable',
      snag: 'No sea, 7°C and grey in December, and a Russian border.',
      area: 'Vake, Tbilisi, Georgia',
      gym: 'Legion BJJ Tbilisi',
      wiki: 'Vake, Tbilisi',
    },
  ],
  kobuleti: [
    {
      name: 'Kobuleti front',
      what: 'The cheapest entry on this list — flats on a long quiet pebble beach.',
      rent: [200, 450],
      mat: '30 min to Batumi; six hours to a mat',
      sea: '2 min',
      shop: 'Village markets, subtropical fruit',
      net: 'Fibre in the town, patchy outside',
      snag: 'Very cheap, very quiet, very wet — it marks the bottom of the range.',
      area: 'Kobuleti, Georgia',
      gym: 'Batumi Boxing Academy',
      wiki: 'Kobuleti',
    },
  ],

  // ── UAE ───────────────────────────────────────────────────────────────────
  jbr: [
    {
      name: 'JBR / Dubai Marina',
      what: 'Furnished 1-beds in towers on the beach, often paid in one or two cheques.',
      rent: [2100, 3300],
      mat: '10 min to Alliance Dubai or The Forge x Roger Gracie',
      sea: '2 min — a running track along the sand, 30°C water',
      shop: '5 min to everything on earth, at Zurich prices',
      net: 'Gigabit, AED 400–600, the most reliable on this list',
      snag: 'Your trip starts in September, which is 38°C and lived indoors.',
      area: 'Jumeirah Beach Residence, Dubai',
      gym: 'Alliance Dubai Jiu Jitsu',
      gymUrl: 'https://alliancedubai.ae/',
      wiki: 'Jumeirah Beach Residence',
    },
  ],
  'dubai-hills': [
    {
      name: 'Dubai Hills Estate',
      what: 'Villa communities where a whole house is realistic, unlike the Marina.',
      rent: [2000, 3000],
      mat: '20 min to the city academies',
      sea: '25 min in traffic',
      shop: 'Dubai Hills Mall on the doorstep',
      net: 'Gigabit fibre',
      snag: 'A suburb in a desert at Tel Aviv rent, where you drive everywhere.',
      area: 'Dubai Hills Estate, Dubai',
      gym: '971 MMA Dubai',
      gymUrl: 'https://971mma.com/',
      wiki: 'Dubai Hills Estate',
    },
  ],
  saadiyat: [
    {
      name: 'Saadiyat Island',
      what: 'More space per dirham than Dubai, on the best natural beach in the UAE.',
      rent: [1900, 2900],
      mat: 'Federation-accredited schools with formal beginner grading',
      sea: '5 min to real sand, turtles, no towers',
      shop: '10 min',
      net: 'Gigabit fibre',
      snag: 'Same five months of heat, and quiet to the point of dull at 21.',
      area: 'Saadiyat Island, Abu Dhabi',
      gym: 'UAE Jiu-Jitsu Federation academy Abu Dhabi',
      wiki: 'Saadiyat Island',
    },
  ],

  // ── Thailand ──────────────────────────────────────────────────────────────
  rawai: [
    {
      name: 'Rawai / Chalong',
      what: '2–3 bed pool villas — the ordinary rental here, not a luxury.',
      rent: [650, 1150],
      mat: '5 min to Tiger Muay Thai, AKA or Southside — start on a Monday from zero',
      sea: '5 min to Nai Harn and Ya Nui',
      shop: '5 min to daily fresh markets',
      net: '฿600 for 500 Mbps; a UPS matters more than the line',
      snag: 'New York opens at 20:30 — you would trade nights, and Sep–Oct is the monsoon.',
      area: 'Rawai, Phuket, Thailand',
      gym: 'Tiger Muay Thai Phuket',
      gymUrl: 'https://www.tigermuaythai.com/',
      wiki: 'Rawai',
    },
  ],
  bangtao: [
    {
      name: 'Cherngtalay / Laguna',
      what: 'Villas in the Laguna area behind 6 km of open sand.',
      rent: [1000, 1800],
      mat: '5 min to Bangtao Muay Thai & MMA',
      sea: '5 min to the best long beach on the island',
      shop: '5 min; the biggest organic scene in Thailand',
      net: 'Fibre, cheap and universal',
      snag: 'The expensive end of Phuket, and the same 20:30 open.',
      area: 'Cherngtalay, Phuket, Thailand',
      gym: 'Bangtao Muay Thai and MMA',
      gymUrl: 'https://bangtaomuaythai.com/',
      wiki: 'Bang Tao',
    },
  ],
  'koh-samui': [
    {
      name: 'Lamai / Maenam',
      what: 'Villas on the quieter side of the island.',
      rent: [650, 1300],
      mat: '10 min to Superpro Samui — four rings, a cage, a big BJJ dojo',
      sea: '3 min to calm Gulf water',
      shop: '5 min',
      net: 'Fibre in the main towns; the island depends on one submarine link',
      snag: 'November is the wettest month of the Samui year at 21 rain days.',
      area: 'Lamai, Ko Samui, Thailand',
      gym: 'Superpro Samui',
      gymUrl: 'https://www.superprosamui.com/',
      wiki: 'Lamai',
    },
  ],
  'chiang-mai': [
    {
      name: 'Nimman / Santitham',
      what: 'Houses with gardens — the cheapest good living on this list.',
      rent: [400, 800],
      mat: '15 min to Tiger Chiang Mai or Santai, taught in English from zero',
      sea: 'None. Mountains and waterfalls',
      shop: 'Northern Thai markets, and the biggest vegan scene in Asia',
      net: 'Gigabit for €20 — the best and cheapest here',
      snag: 'No sea, the 20:30 open, and burning season starts in February.',
      area: 'Nimmanhaemin, Chiang Mai, Thailand',
      gym: 'Tiger Muay Thai Chiang Mai',
      gymUrl: 'https://www.tigermuaythai.com/',
      wiki: 'Chiang Mai',
    },
  ],
  'ao-nang': [
    {
      name: 'Ao Nang',
      what: 'Houses behind the beach road under the limestone.',
      rent: [400, 800],
      mat: 'Muay Thai only; Phuket is three hours',
      sea: '2 min; Railay is 15 by longtail',
      shop: '5 min',
      net: 'Fibre in Ao Nang',
      snag: 'Beautiful and thin — no serious mat, and 19–21 rain days in Sep and Oct.',
      area: 'Ao Nang, Krabi, Thailand',
      gym: 'Ao Nang Muay Thai',
      wiki: 'Ao Nang',
    },
  ],

  // ── Costa Rica ────────────────────────────────────────────────────────────
  tamarindo: [
    {
      name: 'Tamarindo / Langosta',
      what: 'Houses with pools a walk from the surf beach.',
      rent: [1200, 2200],
      mat: '5 min to Hero Academy — BJJ, MMA and boxing, patient coaching',
      sea: '3 min to a beginner-friendly surf beach',
      shop: '5 min; farmers markets and grass-fed beef',
      net: 'Fibre in town, Starlink outside it',
      snag: 'Israel is 8 hours ahead, and Sep–Oct is 20–21 rain days.',
      area: 'Tamarindo, Guanacaste, Costa Rica',
      gym: 'Hero Academy Tamarindo',
      gymUrl: 'https://herobjj.com/',
      wiki: 'Tamarindo, Costa Rica',
    },
  ],
  'santa-teresa': [
    {
      name: 'Santa Teresa / Playa Carmen',
      what: 'Jungle houses a walk from 5 km of near-empty sand.',
      rent: [1000, 2000],
      mat: '5 min to Santa Teresa MMA',
      sea: '2 min to one of the best surf beaches in Central America',
      shop: 'Small organic supply; everything else is trucked in',
      net: 'Fibre arrived recently; most people still run Starlink',
      snag: 'The road is dirt, the hospital is 90 minutes, and getting here is a ferry.',
      area: 'Santa Teresa, Puntarenas, Costa Rica',
      gym: 'Santa Teresa MMA',
      gymUrl: 'https://www.santamma.com/',
      wiki: 'Santa Teresa, Puntarenas',
    },
  ],
  jaco: [
    {
      name: 'Jacó / Playa Hermosa',
      what: 'Condos and small houses, 90 minutes from San José.',
      rent: [900, 1600],
      mat: '5 min to Jaco Jiu Jitsu — a rooftop mat with an ocean view',
      sea: '2 min to grey-sand surf',
      shop: 'Supermarkets and a Friday feria',
      net: 'Fibre',
      snag: 'The party town of the coast, with everything that implies.',
      area: 'Jacó, Costa Rica',
      gym: 'Jaco Jiu Jitsu',
      gymUrl: 'https://www.jacojiujitsu.com/',
      wiki: 'Jacó, Costa Rica',
    },
  ],
  'playas-del-coco': [
    {
      name: 'Playas del Coco',
      what: 'The best value on the Costa Rican coast, in a real town.',
      rent: [800, 1500],
      mat: '5 min to Coco Beach MMA',
      sea: '3 min to a calm swimming bay — rare here',
      shop: 'Decent supermarkets, cheaper than Tamarindo',
      net: 'Fibre',
      snag: 'The driest part of the country — brown and dusty from January.',
      area: 'Playas del Coco, Guanacaste, Costa Rica',
      gym: 'Coco Beach MMA',
      wiki: 'Playas del Coco',
    },
  ],
  uvita: [
    {
      name: 'Uvita hills',
      what: 'Houses in the hills with views over Marino Ballena.',
      rent: [700, 1400],
      mat: 'A small BJJ community, no fixed room',
      sea: '10 min to empty sand and whales',
      shop: 'The best organic farmers market in Costa Rica, Saturdays',
      net: 'Fibre in town, Starlink in the hills',
      snag: 'Over 4,000 mm of rain a year, and 24–25 rain days in Sep and Oct.',
      area: 'Uvita, Costa Rica',
      gym: 'BJJ Dominical Costa Rica',
      wiki: 'Uvita',
    },
  ],

  // ── Mexico ────────────────────────────────────────────────────────────────
  'playa-del-carmen': [
    {
      name: 'Zazil-Ha / Playacar',
      what: '2-beds with a pool, walkable to the beach and Quinta Avenida.',
      rent: [700, 1400],
      mat: '10 min to Gracie Barra Playa — the worldwide fundamentals syllabus',
      sea: '5 min to 28°C Caribbean',
      shop: '5 min; Mercado 28 and Chedraui Selecto',
      net: 'Fibre plus Starlink as a cheap backup',
      snag: 'Sep–Oct is hurricane season, and sargassum can close the beach for weeks.',
      area: 'Zazil-Ha, Playa del Carmen, Mexico',
      gym: 'Gracie Barra Playa del Carmen',
      wiki: 'Playa del Carmen',
    },
  ],
  tulum: [
    {
      name: 'Aldea Zamá',
      what: 'The residential quarter between the town and the beach road.',
      rent: [900, 1800],
      mat: '10 min to Jiujitsu Tulum',
      sea: '10 min by bike to the beach; cenotes inland',
      shop: '5 min',
      net: 'Fibre in the centre; the beach road is unreliable and expensive',
      snag: 'The beach zone runs on generators more often than anyone admits.',
      area: 'Aldea Zamá, Tulum, Mexico',
      gym: 'Jiujitsu Tulum',
      wiki: 'Tulum',
    },
  ],
  'puerto-escondido': [
    {
      name: 'La Punta / Rinconada',
      what: 'Houses in the two neighbourhoods foreigners actually live in.',
      rent: [500, 1000],
      mat: '10 min to La Colonia Jiu Jitsu',
      sea: '2 min; Carrizalillo is the swimming one',
      shop: 'Oaxacan markets at local prices',
      net: 'Fibre in town, and the weak point — run a backup',
      snag: 'Isolated: anywhere else means Mexico City first.',
      area: 'La Punta, Puerto Escondido, Mexico',
      gym: 'La Colonia Jiu Jitsu Puerto Escondido',
      wiki: 'Puerto Escondido, Oaxaca',
    },
  ],
  'puerto-vallarta': [
    {
      name: 'Versalles / Fluvial',
      what: 'The neighbourhoods people actually live in, not the hotel zone.',
      rent: [700, 1300],
      mat: '10 min to the city BJJ clubs',
      sea: '10 min to calm bay water',
      shop: '5 min; a real Mexican city market economy',
      net: 'Fibre',
      snag: 'September is 32°C at 80% humidity with hurricane risk.',
      area: 'Versalles, Puerto Vallarta, Mexico',
      gym: 'BJJ Puerto Vallarta Jalisco',
      wiki: 'Puerto Vallarta',
    },
  ],
  merida: [
    {
      name: 'Centro / Santiago',
      what: 'Colonial houses with a pool and a courtyard, for very little.',
      rent: [500, 1000],
      mat: '10 min — several city academies, almost no foreigners',
      sea: '35 min to Progreso, a flat shallow Gulf beach',
      shop: 'Huge markets, lowest prices of any Mexican city this size',
      net: 'Fibre',
      snag: 'Inland and 38°C in May, with no sea to escape to.',
      area: 'Centro, Mérida, Yucatán, Mexico',
      gym: 'BJJ Merida Yucatan',
      wiki: 'Mérida, Yucatán',
    },
  ],

  // ── Panama ────────────────────────────────────────────────────────────────
  'panama-city': [
    {
      name: 'Costa del Este',
      what: 'Modern high-rise 2-beds in the newest part of the city.',
      rent: [1000, 1800],
      mat: '15 min to the Atos affiliate',
      sea: 'Not swimmable — the beach towns are 60–90 min west',
      shop: 'Everything, in US dollars',
      net: 'The region’s cables land here — 200–600 Mbps',
      snag: 'Sep–Nov are the three wettest months at 19–21 rain days each.',
      area: 'Costa del Este, Panama City, Panama',
      gym: 'Atos Jiu Jitsu Panama',
      wiki: 'Costa del Este',
    },
  ],
  coronado: [
    {
      name: 'Playa Coronado',
      what: 'Houses with pools on a long black-and-white sand beach.',
      rent: [800, 1500],
      mat: '10 min to Playa Coronado BJJ at Nueva Gorgona',
      sea: '5 min',
      shop: '5 min; supermarkets serving a big expat community',
      net: 'Fibre along the coastal highway',
      snag: 'A retirement coast — hot, humid, and the median age is not yours.',
      area: 'Playa Coronado, Panama',
      gym: 'Playa Coronado BJJ',
      wiki: 'Coronado, Panama',
    },
  ],
  bocas: [
    {
      name: 'Bocas Town, Isla Colón',
      what: 'Wooden houses over the water on the main island.',
      rent: [600, 1200],
      mat: '5 min to Bocas Fight Gym — no-gi three evenings a week',
      sea: 'Reef and islands by boat; Red Frog is 20 min',
      shop: 'Island supply — expensive and limited',
      net: 'Fibre reached the island and still goes down',
      snag: 'Nov–Dec are the wettest months at 20–21 rain days, and boats stop when rough.',
      area: 'Bocas Town, Isla Colón, Panama',
      gym: 'Bocas Fight Gym',
      wiki: 'Bocas del Toro',
    },
  ],
  pedasi: [
    {
      name: 'Pedasí village',
      what: 'Village houses 30 minutes from Playa Venao.',
      rent: [500, 1000],
      mat: 'Nothing within an hour',
      sea: '30 min to one of the best surf beaches in Central America',
      shop: 'Village markets and cattle country',
      net: 'Fibre in the village',
      snag: 'Four hours from Panama City, with a clinic rather than a hospital.',
      area: 'Pedasí, Panama',
      gym: 'Atos Jiu Jitsu Panama',
      wiki: 'Pedasí District',
    },
  ],

  // ── United States ─────────────────────────────────────────────────────────
  'fort-lauderdale': [
    {
      name: 'Victoria Park / Las Olas',
      what: 'A 1-bed anywhere near the water, which is what the money buys.',
      rent: [2200, 3500],
      mat: '15 min to American Top Team, Fight Sports or Atos',
      sea: '10 min to warm Atlantic and a beachfront running path',
      shop: '10 min; a large kosher and Israeli food economy in Aventura',
      net: 'Gigabit, and the market is in your time zone',
      snag: 'No right to live there — 90 visa-free days as a visitor, no work rights.',
      area: 'Victoria Park, Fort Lauderdale, Florida',
      gym: 'American Top Team Fort Lauderdale',
      wiki: 'Fort Lauderdale, Florida',
    },
  ],
  'st-petersburg': [
    {
      name: 'Old Northeast, St Petersburg',
      what: 'A house with a yard is realistic here in a way it is not in Miami.',
      rent: [1700, 2600],
      mat: '15 min to South Tampa Jiu-Jitsu — six days a week',
      sea: '15 min to St Pete Beach, calm Gulf water',
      shop: 'Everything, cheaper than South Florida',
      net: 'Gigabit',
      snag: 'Same 90-day visitor limit, and September is peak hurricane season.',
      area: 'Old Northeast, St. Petersburg, Florida',
      gym: 'South Tampa Jiu-Jitsu and MMA',
      gymUrl: 'https://southtampajiujitsu.com/',
      wiki: 'St. Petersburg, Florida',
    },
  ],
  'san-diego': [
    {
      name: 'Pacific Beach',
      what: 'A 1-bed two blocks from the sand, in the American jiu-jitsu mecca.',
      rent: [2400, 3800],
      mat: '5 min to BJJ Revolution; The Arena runs 30+ adult classes a week',
      sea: '3 min; 20°C water in September',
      shop: '5 min; the best farmers markets in the US',
      net: 'Gigabit',
      snag: 'California taxes worldwide income up to 13.3%, and you have 90 days.',
      area: 'Pacific Beach, San Diego, California',
      gym: 'The Arena San Diego',
      gymUrl: 'https://thearenagym.com/jiujitsu/',
      wiki: 'Pacific Beach, San Diego',
    },
  ],
  austin: [
    {
      name: 'South Congress',
      what: 'A 1-bed in the walkable part of a landlocked city.',
      rent: [1600, 2600],
      mat: '10 min to Gracie Humaitá Austin or Onnit',
      sea: 'None. Lakes and rivers',
      shop: 'Very good, and no state income tax',
      net: 'Gigabit',
      snag: 'Landlocked, 38°C for four months, and the same 90-day limit.',
      area: 'South Congress, Austin, Texas',
      gym: 'Gracie Humaita Austin',
      wiki: 'South Congress',
    },
  ],
}

export function spotsFor(id: PlaceId): Spot[] {
  return SPOTS[id] ?? []
}

/** Every country now carries street-level detail. */
export const DETAILED_COUNTRIES = [
  'malta', 'italy', 'spain', 'greece', 'cyprus',
  'portugal', 'croatia', 'montenegro', 'albania', 'bulgaria',
  'poland', 'georgia', 'uae', 'thailand', 'costa-rica',
  'mexico', 'panama', 'usa',
]
