/**
 * Prop-firm plan catalogues — generated, do not edit by hand.
 *
 * Rebuilt by scripts/import-catalogue.mts from the published spec sheets.
 * These are starting points: firm terms change constantly, so every value is
 * editable on the firm's catalogue once applied, and an account can diverge
 * from the plan it came from.
 *
 * Verified against the source specs on 2026-08-22.
 */
import type { FirmPlan } from '@/db/schema'

export type FirmCatalogue = {
  slug: string
  name: string
  website: string
  plans: FirmPlan[]
}

export const FIRM_CATALOGUES: FirmCatalogue[] = [
  {
    "name": "Lucid Trading",
    "website": "https://lucidtrading.com",
    "slug": "lucid",
    "plans": [
      {
        "label": "LucidPro $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": 1000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 1250,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 94.5,
        "profitSplit": 0.9,
        "maxContracts": 2,
        "maxMicroContracts": 20,
        "activationFee": 0,
        "resetFee": 90,
        "buffer": 1100,
        "payoutFrequency": "Every 3 trading days",
        "minPayout": "$500",
        "notes": "Buffer: $26,100 · Max payout: 1st $1,000 · 2+ $1,500 · Min balance to request: $26,100+"
      },
      {
        "label": "LucidPro $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 3000,
        "dailyLossLimit": 1200,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 129.5,
        "profitSplit": 0.9,
        "maxContracts": 4,
        "maxMicroContracts": 40,
        "activationFee": 0,
        "resetFee": 120,
        "buffer": 2100,
        "payoutFrequency": "Every 3 trading days",
        "minPayout": "$500",
        "notes": "Buffer: $52,100 · Max payout: 1st $2,000 · 2+ $2,500 · Min balance to request: $52,100+"
      },
      {
        "label": "LucidPro $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 6000,
        "dailyLossLimit": 1800,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 199.5,
        "profitSplit": 0.9,
        "maxContracts": 6,
        "maxMicroContracts": 60,
        "activationFee": 0,
        "resetFee": 180,
        "buffer": 3100,
        "payoutFrequency": "Every 3 trading days",
        "minPayout": "$500",
        "notes": "Buffer: $103,100 · Max payout: 1st $2,500 · 2+ $3,000 · Min balance to request: $103,100+"
      },
      {
        "label": "LucidPro $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": 4500,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 9000,
        "dailyLossLimit": 2700,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 259,
        "profitSplit": 0.9,
        "maxContracts": 10,
        "maxMicroContracts": 100,
        "activationFee": 0,
        "resetFee": 245,
        "buffer": 4600,
        "payoutFrequency": "Every 3 trading days",
        "minPayout": "$500",
        "notes": "Buffer: $154,600 · Max payout: 1st $3,000 · 2+ $3,500 · Min balance to request: $154,600+"
      },
      {
        "label": "LucidFlex $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": 1000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 1250,
        "dailyLossLimit": null,
        "minTradingDays": 2,
        "minWinningDays": 5,
        "winningDayMinProfit": 100,
        "cost": 70,
        "profitSplit": 0.9,
        "maxContracts": 2,
        "maxMicroContracts": 20,
        "activationFee": 0,
        "resetFee": 60,
        "buffer": null,
        "payoutFrequency": "Every 5 winning days",
        "minPayout": "$500",
        "notes": "Max payout: 50% of profit, up to $1,000 · Scaling: Yes (LucidScale)"
      },
      {
        "label": "LucidFlex $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 3000,
        "dailyLossLimit": null,
        "minTradingDays": 2,
        "minWinningDays": 5,
        "winningDayMinProfit": 150,
        "cost": 98,
        "profitSplit": 0.9,
        "maxContracts": 4,
        "maxMicroContracts": 40,
        "activationFee": 0,
        "resetFee": 95,
        "buffer": null,
        "payoutFrequency": "Every 5 winning days",
        "minPayout": "$500",
        "notes": "Max payout: 50% of profit, up to $2,000 · Scaling: Yes (LucidScale)"
      },
      {
        "label": "LucidFlex $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 6000,
        "dailyLossLimit": null,
        "minTradingDays": 2,
        "minWinningDays": 5,
        "winningDayMinProfit": 200,
        "cost": 157.5,
        "profitSplit": 0.9,
        "maxContracts": 6,
        "maxMicroContracts": 60,
        "activationFee": 0,
        "resetFee": 140,
        "buffer": null,
        "payoutFrequency": "Every 5 winning days",
        "minPayout": "$500",
        "notes": "Max payout: 50% of profit, up to $2,500 · Scaling: Yes (LucidScale)"
      },
      {
        "label": "LucidFlex $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": 4500,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 9000,
        "dailyLossLimit": null,
        "minTradingDays": 2,
        "minWinningDays": 5,
        "winningDayMinProfit": 250,
        "cost": 294,
        "profitSplit": 0.9,
        "maxContracts": 10,
        "maxMicroContracts": 100,
        "activationFee": 0,
        "resetFee": 280,
        "buffer": null,
        "payoutFrequency": "Every 5 winning days",
        "minPayout": "$500",
        "notes": "Max payout: 50% of profit, up to $3,000 · Scaling: Yes (LucidScale)"
      },
      {
        "label": "LucidDirect $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": null,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 238,
        "profitSplit": 0.9,
        "maxContracts": 2,
        "maxMicroContracts": 20,
        "activationFee": 0,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": "Every 5 trading days",
        "minPayout": "$500",
        "notes": "Buffer: — · Max payout: 1–3 $1,000 · 4–5 $1,000"
      },
      {
        "label": "LucidDirect $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": null,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 364,
        "profitSplit": 0.9,
        "maxContracts": 4,
        "maxMicroContracts": 40,
        "activationFee": 0,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": "Every 5 trading days",
        "minPayout": "$500",
        "notes": "Buffer: — · Max payout: 1–3 $2,000 · 4–5 $2,500"
      },
      {
        "label": "LucidDirect $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": null,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 490,
        "profitSplit": 0.9,
        "maxContracts": 6,
        "maxMicroContracts": 60,
        "activationFee": 0,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": "Every 5 trading days",
        "minPayout": "$500",
        "notes": "Buffer: — · Max payout: 1–3 $2,500 · 4–5 $3,000"
      },
      {
        "label": "LucidDirect $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": null,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 588,
        "profitSplit": 0.9,
        "maxContracts": 10,
        "maxMicroContracts": 100,
        "activationFee": 0,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": "Every 5 trading days",
        "minPayout": "$500",
        "notes": "Buffer: — · Max payout: 1–3 $3,000 · 4–5 $3,500"
      },
      {
        "label": "LucidDaily $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": 1000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 1250,
        "dailyLossLimit": 600,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": null,
        "profitSplit": 0.9,
        "maxContracts": 2,
        "maxMicroContracts": 20,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 1100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Evaluation drawdown defaults to EOD but is switchable to intraday when you buy, and the daily loss limit can be switched off — set both on the account to match what you actually bought · Funded drawdown is intraday and the daily loss limit still applies · 50% consistency in evaluation, none once funded · Micro scaling 10:1"
      },
      {
        "label": "LucidDaily $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 3000,
        "dailyLossLimit": 1200,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": null,
        "profitSplit": 0.9,
        "maxContracts": 4,
        "maxMicroContracts": 40,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 2100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Evaluation drawdown defaults to EOD but is switchable to intraday when you buy, and the daily loss limit can be switched off — set both on the account to match what you actually bought · Funded drawdown is intraday and the daily loss limit still applies · 50% consistency in evaluation, none once funded · Micro scaling 10:1"
      },
      {
        "label": "LucidDaily $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 6000,
        "dailyLossLimit": 1800,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": null,
        "profitSplit": 0.9,
        "maxContracts": 6,
        "maxMicroContracts": 60,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 3100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Evaluation drawdown defaults to EOD but is switchable to intraday when you buy, and the daily loss limit can be switched off — set both on the account to match what you actually bought · Funded drawdown is intraday and the daily loss limit still applies · 50% consistency in evaluation, none once funded · Micro scaling 10:1"
      },
      {
        "label": "LucidDaily $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": 4500,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 9000,
        "dailyLossLimit": 2700,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": null,
        "profitSplit": 0.9,
        "maxContracts": 10,
        "maxMicroContracts": 100,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 4600,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Evaluation drawdown defaults to EOD but is switchable to intraday when you buy, and the daily loss limit can be switched off — set both on the account to match what you actually bought · Funded drawdown is intraday and the daily loss limit still applies · 50% consistency in evaluation, none once funded · Micro scaling 10:1"
      }
    ]
  },
  {
    "name": "Tradeify",
    "website": "https://tradeify.co",
    "slug": "tradeify",
    "plans": [
      {
        "label": "Growth $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": 1000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 1500,
        "dailyLossLimit": 600,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 100,
        "cost": 59,
        "profitSplit": 0.9,
        "maxContracts": 1,
        "maxMicroContracts": 10,
        "activationFee": null,
        "resetFee": 60,
        "buffer": null,
        "payoutFrequency": "Every 5 days",
        "minPayout": "$500",
        "notes": "Buffer: —"
      },
      {
        "label": "Growth $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 3000,
        "dailyLossLimit": 1250,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 150,
        "cost": 87,
        "profitSplit": 0.9,
        "maxContracts": 4,
        "maxMicroContracts": 40,
        "activationFee": null,
        "resetFee": 95,
        "buffer": null,
        "payoutFrequency": "Every 5 days",
        "minPayout": "$500",
        "notes": "Buffer: —"
      },
      {
        "label": "Growth $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3500,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 6000,
        "dailyLossLimit": 2500,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 200,
        "cost": 153,
        "profitSplit": 0.9,
        "maxContracts": 8,
        "maxMicroContracts": 80,
        "activationFee": null,
        "resetFee": 169,
        "buffer": null,
        "payoutFrequency": "Every 5 days",
        "minPayout": "$500",
        "notes": "Buffer: —"
      },
      {
        "label": "Growth $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": 5000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 9000,
        "dailyLossLimit": 3750,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 250,
        "cost": 221,
        "profitSplit": 0.9,
        "maxContracts": 12,
        "maxMicroContracts": 120,
        "activationFee": null,
        "resetFee": 229,
        "buffer": null,
        "payoutFrequency": "Every 5 days",
        "minPayout": "$500",
        "notes": "Buffer: —"
      },
      {
        "label": "Select (Flex) $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": 1000,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": 1500,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 100,
        "cost": 65,
        "profitSplit": null,
        "maxContracts": 1,
        "maxMicroContracts": 10,
        "activationFee": null,
        "resetFee": 65,
        "buffer": null,
        "payoutFrequency": "Every 5 winning days",
        "minPayout": null,
        "notes": "Max payout: 50% of profit, up to $1,250"
      },
      {
        "label": "Select (Flex) $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": 3000,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 150,
        "cost": 99,
        "profitSplit": null,
        "maxContracts": 4,
        "maxMicroContracts": 40,
        "activationFee": null,
        "resetFee": 99,
        "buffer": null,
        "payoutFrequency": "Every 5 winning days",
        "minPayout": null,
        "notes": "Max payout: 50% of profit, up to $3,000"
      },
      {
        "label": "Select (Flex) $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3000,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": 6000,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 200,
        "cost": 159,
        "profitSplit": null,
        "maxContracts": 8,
        "maxMicroContracts": 80,
        "activationFee": null,
        "resetFee": 155,
        "buffer": null,
        "payoutFrequency": "Every 5 winning days",
        "minPayout": null,
        "notes": "Max payout: 50% of profit, up to $4,000"
      },
      {
        "label": "Select (Flex) $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": 4500,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": 9000,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 250,
        "cost": 221,
        "profitSplit": null,
        "maxContracts": 12,
        "maxMicroContracts": 120,
        "activationFee": null,
        "resetFee": 215,
        "buffer": null,
        "payoutFrequency": "Every 5 winning days",
        "minPayout": null,
        "notes": "Max payout: 50% of profit, up to $5,000"
      },
      {
        "label": "Select (Daily) $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": 1000,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": 1500,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 65,
        "profitSplit": null,
        "maxContracts": 1,
        "maxMicroContracts": 10,
        "activationFee": null,
        "resetFee": 65,
        "buffer": null,
        "payoutFrequency": "Daily",
        "minPayout": null,
        "notes": "Buffer: Buffer must be cleared first · Max payout: $600 per payout"
      },
      {
        "label": "Select (Daily) $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": 3000,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 99,
        "profitSplit": null,
        "maxContracts": 4,
        "maxMicroContracts": 40,
        "activationFee": null,
        "resetFee": 99,
        "buffer": null,
        "payoutFrequency": "Daily",
        "minPayout": null,
        "notes": "Buffer: Buffer must be cleared first · Max payout: $1,000 per payout"
      },
      {
        "label": "Select (Daily) $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3000,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": 6000,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 159,
        "profitSplit": null,
        "maxContracts": 8,
        "maxMicroContracts": 80,
        "activationFee": null,
        "resetFee": 155,
        "buffer": null,
        "payoutFrequency": "Daily",
        "minPayout": null,
        "notes": "Buffer: Buffer must be cleared first · Max payout: $1,500 per payout"
      },
      {
        "label": "Select (Daily) $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": 4500,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": 9000,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 221,
        "profitSplit": null,
        "maxContracts": 12,
        "maxMicroContracts": 120,
        "activationFee": null,
        "resetFee": 215,
        "buffer": null,
        "payoutFrequency": "Daily",
        "minPayout": null,
        "notes": "Buffer: Buffer must be cleared first · Max payout: $2,500 per payout"
      },
      {
        "label": "Lightning $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": null,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 207,
        "profitSplit": 0.9,
        "maxContracts": 1,
        "maxMicroContracts": 10,
        "activationFee": 0,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": "Every 5 days",
        "minPayout": "$500",
        "notes": "Buffer: —"
      },
      {
        "label": "Lightning $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": null,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 295,
        "profitSplit": 0.9,
        "maxContracts": 4,
        "maxMicroContracts": 40,
        "activationFee": 0,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": "Every 5 days",
        "minPayout": "$500",
        "notes": "Buffer: —"
      },
      {
        "label": "Lightning $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": null,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 396,
        "profitSplit": 0.9,
        "maxContracts": 8,
        "maxMicroContracts": 80,
        "activationFee": 0,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": "Every 5 days",
        "minPayout": "$500",
        "notes": "Buffer: —"
      },
      {
        "label": "Lightning $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": null,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 478,
        "profitSplit": 0.9,
        "maxContracts": 12,
        "maxMicroContracts": 120,
        "activationFee": 0,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": "Every 5 days",
        "minPayout": "$500",
        "notes": "Buffer: —"
      }
    ]
  },
  {
    "name": "Take Profit Trader",
    "website": "https://takeprofittrader.com",
    "slug": "take-profit-trader",
    "plans": [
      {
        "label": "Take Profit Trader $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": 1500,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 1500,
        "dailyLossLimit": null,
        "minTradingDays": 5,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 150,
        "profitSplit": null,
        "maxContracts": 3,
        "maxMicroContracts": null,
        "activationFee": null,
        "resetFee": null,
        "buffer": 1600,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $1,600 (drawdown + $100) · Max payout: No cap"
      },
      {
        "label": "Take Profit Trader $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 3000,
        "dailyLossLimit": null,
        "minTradingDays": 5,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 170,
        "profitSplit": null,
        "maxContracts": 6,
        "maxMicroContracts": null,
        "activationFee": null,
        "resetFee": null,
        "buffer": 2100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $2,100 (drawdown + $100) · Max payout: No cap"
      },
      {
        "label": "Take Profit Trader $75k",
        "phase": "eval",
        "size": 75000,
        "maxDrawdown": 2500,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 4500,
        "dailyLossLimit": null,
        "minTradingDays": 5,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 245,
        "profitSplit": null,
        "maxContracts": 9,
        "maxMicroContracts": null,
        "activationFee": null,
        "resetFee": null,
        "buffer": 2600,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $2,600 (drawdown + $100) · Max payout: No cap"
      },
      {
        "label": "Take Profit Trader $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 6000,
        "dailyLossLimit": null,
        "minTradingDays": 5,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 330,
        "profitSplit": null,
        "maxContracts": 12,
        "maxMicroContracts": null,
        "activationFee": null,
        "resetFee": null,
        "buffer": 3100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $3,100 (drawdown + $100) · Max payout: No cap"
      },
      {
        "label": "Take Profit Trader $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": 4500,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 9000,
        "dailyLossLimit": null,
        "minTradingDays": 5,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 360,
        "profitSplit": null,
        "maxContracts": 15,
        "maxMicroContracts": null,
        "activationFee": null,
        "resetFee": null,
        "buffer": 4600,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $4,600 (drawdown + $100) · Max payout: No cap"
      }
    ]
  },
  {
    "name": "Alpha Futures",
    "website": "https://alpha-futures.com",
    "slug": "alpha-futures",
    "plans": [
      {
        "label": "Premium $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 3000,
        "dailyLossLimit": null,
        "minTradingDays": 2,
        "minWinningDays": 5,
        "winningDayMinProfit": 200,
        "cost": 159,
        "profitSplit": 0.9,
        "maxContracts": 4,
        "maxMicroContracts": 40,
        "activationFee": null,
        "resetFee": 149,
        "buffer": null,
        "payoutFrequency": "Weekly",
        "minPayout": "$500",
        "notes": "Buffer: — · Max payout: 1st $2,000 → 5th+ $4,000 · Scaling: Yes"
      },
      {
        "label": "Premium $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 6000,
        "dailyLossLimit": null,
        "minTradingDays": 2,
        "minWinningDays": 5,
        "winningDayMinProfit": 200,
        "cost": 269,
        "profitSplit": 0.9,
        "maxContracts": 8,
        "maxMicroContracts": 80,
        "activationFee": null,
        "resetFee": 239,
        "buffer": null,
        "payoutFrequency": "Weekly",
        "minPayout": "$500",
        "notes": "Buffer: — · Max payout: 1st $2,500 → 5th+ $5,000 · Scaling: Yes"
      },
      {
        "label": "Premium $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": 4500,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 9000,
        "dailyLossLimit": null,
        "minTradingDays": 2,
        "minWinningDays": 5,
        "winningDayMinProfit": 200,
        "cost": 379,
        "profitSplit": 0.9,
        "maxContracts": 12,
        "maxMicroContracts": 120,
        "activationFee": null,
        "resetFee": 329,
        "buffer": null,
        "payoutFrequency": "Weekly",
        "minPayout": "$500",
        "notes": "Buffer: — · Max payout: 1st $3,000 → 5th+ $6,000 · Scaling: Yes"
      },
      {
        "label": "Advanced $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 1750,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 4000,
        "dailyLossLimit": null,
        "minTradingDays": 2,
        "minWinningDays": 5,
        "winningDayMinProfit": 200,
        "cost": 209,
        "profitSplit": 0.9,
        "maxContracts": 5,
        "maxMicroContracts": 50,
        "activationFee": null,
        "resetFee": 209,
        "buffer": null,
        "payoutFrequency": "Weekly",
        "minPayout": "$1,000",
        "notes": "Buffer: — · Max payout: $15,000 per request · Scaling: No — full size from start"
      },
      {
        "label": "Advanced $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3500,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 8000,
        "dailyLossLimit": null,
        "minTradingDays": 2,
        "minWinningDays": 5,
        "winningDayMinProfit": 200,
        "cost": 349,
        "profitSplit": 0.9,
        "maxContracts": 10,
        "maxMicroContracts": 100,
        "activationFee": null,
        "resetFee": 349,
        "buffer": null,
        "payoutFrequency": "Weekly",
        "minPayout": "$1,000",
        "notes": "Buffer: — · Max payout: $15,000 per request · Scaling: No — full size from start"
      },
      {
        "label": "Advanced $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": 5250,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 12000,
        "dailyLossLimit": null,
        "minTradingDays": 2,
        "minWinningDays": 5,
        "winningDayMinProfit": 200,
        "cost": 489,
        "profitSplit": 0.9,
        "maxContracts": 15,
        "maxMicroContracts": 150,
        "activationFee": null,
        "resetFee": 489,
        "buffer": null,
        "payoutFrequency": "Weekly",
        "minPayout": "$1,000",
        "notes": "Buffer: — · Max payout: $15,000 per request · Scaling: No — full size from start"
      },
      {
        "label": "Zero $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": 1000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 1500,
        "dailyLossLimit": 500,
        "minTradingDays": 1,
        "minWinningDays": 5,
        "winningDayMinProfit": 200,
        "cost": 79,
        "profitSplit": 0.9,
        "maxContracts": 1,
        "maxMicroContracts": 10,
        "activationFee": 0,
        "resetFee": 69,
        "buffer": null,
        "payoutFrequency": "Every 5 winning days of $200+",
        "minPayout": "$200",
        "notes": "Buffer: — · Max payout: 50% of profit, up to $1,000 · Scaling: No"
      },
      {
        "label": "Zero $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 3000,
        "dailyLossLimit": 1000,
        "minTradingDays": 1,
        "minWinningDays": 5,
        "winningDayMinProfit": 200,
        "cost": 119,
        "profitSplit": 0.9,
        "maxContracts": 3,
        "maxMicroContracts": 30,
        "activationFee": 0,
        "resetFee": 109,
        "buffer": null,
        "payoutFrequency": "Every 5 winning days of $200+",
        "minPayout": "$200",
        "notes": "Buffer: — · Max payout: 50% of profit, up to $1,500 · Scaling: Yes"
      },
      {
        "label": "Zero $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 6000,
        "dailyLossLimit": 2000,
        "minTradingDays": 1,
        "minWinningDays": 5,
        "winningDayMinProfit": 200,
        "cost": 239,
        "profitSplit": 0.9,
        "maxContracts": 6,
        "maxMicroContracts": 60,
        "activationFee": 0,
        "resetFee": 219,
        "buffer": null,
        "payoutFrequency": "Every 5 winning days of $200+",
        "minPayout": "$200",
        "notes": "Buffer: — · Max payout: 50% of profit, up to $2,500 · Scaling: Yes"
      },
      {
        "label": "Direct $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": null,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 349,
        "profitSplit": 0.9,
        "maxContracts": 2,
        "maxMicroContracts": 20,
        "activationFee": null,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": "Up to 4× / month",
        "minPayout": "$500",
        "notes": "Buffer: — · Max payout: $1,000 per request · Scaling: No — full size from start"
      },
      {
        "label": "Direct $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": null,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 519,
        "profitSplit": 0.9,
        "maxContracts": 4,
        "maxMicroContracts": 40,
        "activationFee": null,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": "Up to 4× / month",
        "minPayout": "$500",
        "notes": "Buffer: — · Max payout: $2,000 per request · Scaling: No — full size from start"
      },
      {
        "label": "Direct $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": null,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 689,
        "profitSplit": 0.9,
        "maxContracts": 8,
        "maxMicroContracts": 80,
        "activationFee": null,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": "Up to 4× / month",
        "minPayout": "$500",
        "notes": "Buffer: — · Max payout: $2,500 per request · Scaling: No — full size from start"
      },
      {
        "label": "Direct $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": null,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 859,
        "profitSplit": 0.9,
        "maxContracts": 10,
        "maxMicroContracts": 100,
        "activationFee": null,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": "Up to 4× / month",
        "minPayout": "$500",
        "notes": "Buffer: — · Max payout: $3,000 per request · Scaling: No — full size from start"
      }
    ]
  },
  {
    "name": "FundedNext",
    "website": "https://fundednext.com",
    "slug": "fundednext",
    "plans": [
      {
        "label": "Flex $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": null,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 249.99,
        "profitSplit": null,
        "maxContracts": null,
        "maxMicroContracts": null,
        "activationFee": null,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: —"
      },
      {
        "label": "Flex $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": null,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 129.99,
        "profitSplit": null,
        "maxContracts": null,
        "maxMicroContracts": null,
        "activationFee": null,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: —"
      },
      {
        "label": "Flex $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": null,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 69.99,
        "profitSplit": null,
        "maxContracts": null,
        "maxMicroContracts": null,
        "activationFee": null,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: —"
      },
      {
        "label": "Legacy $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": null,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 239.99,
        "profitSplit": null,
        "maxContracts": null,
        "maxMicroContracts": null,
        "activationFee": null,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: —"
      },
      {
        "label": "Legacy $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": null,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 199.99,
        "profitSplit": null,
        "maxContracts": null,
        "maxMicroContracts": null,
        "activationFee": null,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: —"
      },
      {
        "label": "Legacy $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": null,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 79.99,
        "profitSplit": null,
        "maxContracts": null,
        "maxMicroContracts": null,
        "activationFee": null,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: —"
      },
      {
        "label": "Rapid $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": null,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 279.99,
        "profitSplit": null,
        "maxContracts": null,
        "maxMicroContracts": null,
        "activationFee": null,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: —"
      },
      {
        "label": "Rapid $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": null,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 169.99,
        "profitSplit": null,
        "maxContracts": null,
        "maxMicroContracts": null,
        "activationFee": null,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: —"
      },
      {
        "label": "Rapid $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": null,
        "drawdownType": "none",
        "consistencyPercent": null,
        "profitTarget": null,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": 79.99,
        "profitSplit": null,
        "maxContracts": null,
        "maxMicroContracts": null,
        "activationFee": null,
        "resetFee": null,
        "buffer": null,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: —"
      }
    ]
  },
  {
    "name": "Apex Trader Funding",
    "website": "https://apextraderfunding.com",
    "slug": "apex",
    "plans": [
      {
        "label": "Performance Account (Intraday|Standard) $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": 1000,
        "drawdownType": "trailing_intraday",
        "consistencyPercent": null,
        "profitTarget": 1500,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 100,
        "cost": 19.9,
        "profitSplit": null,
        "maxContracts": 4,
        "maxMicroContracts": 40,
        "activationFee": 69,
        "resetFee": null,
        "buffer": 1100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $26,100 · Min balance to request: $26,600"
      },
      {
        "label": "Performance Account (Intraday|Standard) $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "trailing_intraday",
        "consistencyPercent": null,
        "profitTarget": 3000,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 250,
        "cost": 24.9,
        "profitSplit": null,
        "maxContracts": 6,
        "maxMicroContracts": 60,
        "activationFee": 79,
        "resetFee": null,
        "buffer": 2100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $52,100 · Min balance to request: $52,600"
      },
      {
        "label": "Performance Account (Intraday|Standard) $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3000,
        "drawdownType": "trailing_intraday",
        "consistencyPercent": null,
        "profitTarget": 6000,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 300,
        "cost": 39.9,
        "profitSplit": null,
        "maxContracts": 8,
        "maxMicroContracts": 80,
        "activationFee": 99,
        "resetFee": null,
        "buffer": 3100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $103,100 · Min balance to request: $103,600"
      },
      {
        "label": "Performance Account (Intraday|Standard) $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": 4000,
        "drawdownType": "trailing_intraday",
        "consistencyPercent": null,
        "profitTarget": 9000,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 350,
        "cost": 59.9,
        "profitSplit": null,
        "maxContracts": 12,
        "maxMicroContracts": 120,
        "activationFee": 129,
        "resetFee": null,
        "buffer": 4100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $154,100 · Min balance to request: $154,600"
      },
      {
        "label": "Performance Account (Intraday|No activation fee) $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": 1000,
        "drawdownType": "trailing_intraday",
        "consistencyPercent": null,
        "profitTarget": 1500,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 100,
        "cost": 69,
        "profitSplit": null,
        "maxContracts": 4,
        "maxMicroContracts": 40,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 1100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $26,100 · Min balance to request: $26,600"
      },
      {
        "label": "Performance Account (Intraday|No activation fee) $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "trailing_intraday",
        "consistencyPercent": null,
        "profitTarget": 3000,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 250,
        "cost": 79,
        "profitSplit": null,
        "maxContracts": 6,
        "maxMicroContracts": 60,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 2100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $52,100 · Min balance to request: $52,600"
      },
      {
        "label": "Performance Account (Intraday|No activation fee) $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3000,
        "drawdownType": "trailing_intraday",
        "consistencyPercent": null,
        "profitTarget": 6000,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 300,
        "cost": 109,
        "profitSplit": null,
        "maxContracts": 8,
        "maxMicroContracts": 80,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 3100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $103,100 · Min balance to request: $103,600"
      },
      {
        "label": "Performance Account (Intraday|No activation fee) $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": 4000,
        "drawdownType": "trailing_intraday",
        "consistencyPercent": null,
        "profitTarget": 9000,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 350,
        "cost": 169,
        "profitSplit": null,
        "maxContracts": 12,
        "maxMicroContracts": 120,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 4100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $154,100 · Min balance to request: $154,600"
      },
      {
        "label": "Performance Account (EOD|Standard) $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": 1000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 1500,
        "dailyLossLimit": 500,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 100,
        "cost": 39,
        "profitSplit": null,
        "maxContracts": 4,
        "maxMicroContracts": 40,
        "activationFee": 89,
        "resetFee": null,
        "buffer": 1100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $26,100 · Min balance to request: $26,600"
      },
      {
        "label": "Performance Account (EOD|Standard) $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 3000,
        "dailyLossLimit": 1000,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 250,
        "cost": 45,
        "profitSplit": null,
        "maxContracts": 6,
        "maxMicroContracts": 60,
        "activationFee": 99,
        "resetFee": null,
        "buffer": 2100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $52,100 · Min balance to request: $52,600"
      },
      {
        "label": "Performance Account (EOD|Standard) $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 6000,
        "dailyLossLimit": 1500,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 300,
        "cost": 59,
        "profitSplit": null,
        "maxContracts": 8,
        "maxMicroContracts": 80,
        "activationFee": 119,
        "resetFee": null,
        "buffer": 3100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $103,100 · Min balance to request: $103,600"
      },
      {
        "label": "Performance Account (EOD|Standard) $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": 4000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 9000,
        "dailyLossLimit": 2000,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 350,
        "cost": 109,
        "profitSplit": null,
        "maxContracts": 12,
        "maxMicroContracts": 120,
        "activationFee": 149,
        "resetFee": null,
        "buffer": 4100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $154,100 · Min balance to request: $154,600"
      },
      {
        "label": "Performance Account (EOD|No activation fee) $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": 1000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 1500,
        "dailyLossLimit": 500,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 100,
        "cost": 89,
        "profitSplit": null,
        "maxContracts": 4,
        "maxMicroContracts": 40,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 1100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $26,100 · Min balance to request: $26,600"
      },
      {
        "label": "Performance Account (EOD|No activation fee) $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 3000,
        "dailyLossLimit": 1000,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 250,
        "cost": 109,
        "profitSplit": null,
        "maxContracts": 6,
        "maxMicroContracts": 60,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 2100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $52,100 · Min balance to request: $52,600"
      },
      {
        "label": "Performance Account (EOD|No activation fee) $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 6000,
        "dailyLossLimit": 1500,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 300,
        "cost": 139,
        "profitSplit": null,
        "maxContracts": 8,
        "maxMicroContracts": 80,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 3100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $103,100 · Min balance to request: $103,600"
      },
      {
        "label": "Performance Account (EOD|No activation fee) $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": 4000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 9000,
        "dailyLossLimit": 2000,
        "minTradingDays": null,
        "minWinningDays": 5,
        "winningDayMinProfit": 350,
        "cost": 229,
        "profitSplit": null,
        "maxContracts": 12,
        "maxMicroContracts": 120,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 4100,
        "payoutFrequency": null,
        "minPayout": null,
        "notes": "Buffer: $154,100 · Min balance to request: $154,600"
      }
    ]
  },
  {
    "slug": "myfundedfutures",
    "name": "MyFundedFutures",
    "website": "https://myfundedfutures.com",
    "plans": [
      {
        "label": "Rapid $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": 1000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 1500,
        "dailyLossLimit": null,
        "minTradingDays": 1,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": null,
        "profitSplit": 0.9,
        "maxContracts": 3,
        "maxMicroContracts": 30,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 1100,
        "payoutFrequency": "From 1 day",
        "minPayout": "$500",
        "notes": "Funded drawdown is real-time, not EOD · Micro scaling 10:1 · No funded consistency · No scaling rule"
      },
      {
        "label": "Rapid $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 3000,
        "dailyLossLimit": null,
        "minTradingDays": 1,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": null,
        "profitSplit": 0.9,
        "maxContracts": 5,
        "maxMicroContracts": 50,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 2100,
        "payoutFrequency": "From 1 day",
        "minPayout": "$500",
        "notes": "Funded drawdown is real-time, not EOD · Micro scaling 10:1 · No funded consistency · No scaling rule"
      },
      {
        "label": "Rapid $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 6000,
        "dailyLossLimit": null,
        "minTradingDays": 1,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": null,
        "profitSplit": 0.9,
        "maxContracts": 8,
        "maxMicroContracts": 80,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 3100,
        "payoutFrequency": "From 1 day",
        "minPayout": "$500",
        "notes": "Funded drawdown is real-time, not EOD · Micro scaling 10:1 · No funded consistency · No scaling rule"
      },
      {
        "label": "Rapid $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": 4500,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 9000,
        "dailyLossLimit": null,
        "minTradingDays": 1,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": null,
        "profitSplit": 0.9,
        "maxContracts": 10,
        "maxMicroContracts": 100,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 4600,
        "payoutFrequency": "From 1 day",
        "minPayout": "$500",
        "notes": "Funded drawdown is real-time, not EOD · Micro scaling 10:1 · No funded consistency · No scaling rule"
      },
      {
        "label": "Rapid EOD $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.3,
        "profitTarget": 3000,
        "dailyLossLimit": null,
        "minTradingDays": null,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": null,
        "profitSplit": 0.9,
        "maxContracts": 3,
        "maxMicroContracts": 30,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 2100,
        "payoutFrequency": "Daily",
        "minPayout": "$500",
        "notes": "Drawdown stays EOD once funded, unlike plain Rapid · Same 3 contracts and 10:1 micro scaling in both phases · No daily drawdown · No funded consistency · No scaling rule · $500 net profit required between payouts"
      },
      {
        "label": "Pro $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 3000,
        "dailyLossLimit": null,
        "minTradingDays": 14,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": null,
        "profitSplit": 0.8,
        "maxContracts": 3,
        "maxMicroContracts": 30,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 2100,
        "payoutFrequency": "From 14 days",
        "minPayout": "$1,000",
        "notes": "EOD drawdown in both phases · Micro scaling 10:1 in evaluation, none once funded · Contract ceiling rises when funded · No funded consistency · No activation fee · Funded: 5 contracts"
      },
      {
        "label": "Pro $100k",
        "phase": "eval",
        "size": 100000,
        "maxDrawdown": 3000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 6000,
        "dailyLossLimit": null,
        "minTradingDays": 14,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": null,
        "profitSplit": 0.8,
        "maxContracts": 6,
        "maxMicroContracts": 60,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 3100,
        "payoutFrequency": "From 14 days",
        "minPayout": "$1,000",
        "notes": "EOD drawdown in both phases · Micro scaling 10:1 in evaluation, none once funded · Contract ceiling rises when funded · No funded consistency · No activation fee · Funded: 10 contracts"
      },
      {
        "label": "Pro $150k",
        "phase": "eval",
        "size": 150000,
        "maxDrawdown": 4500,
        "drawdownType": "trailing_eod",
        "consistencyPercent": 0.5,
        "profitTarget": 9000,
        "dailyLossLimit": null,
        "minTradingDays": 14,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": null,
        "profitSplit": 0.8,
        "maxContracts": 9,
        "maxMicroContracts": 90,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 4600,
        "payoutFrequency": "From 14 days",
        "minPayout": "$1,000",
        "notes": "EOD drawdown in both phases · Micro scaling 10:1 in evaluation, none once funded · Contract ceiling rises when funded · No funded consistency · No activation fee · Funded: 15 contracts"
      },
      {
        "label": "Builder $25k",
        "phase": "eval",
        "size": 25000,
        "maxDrawdown": 1000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 1500,
        "dailyLossLimit": null,
        "minTradingDays": 2,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": null,
        "profitSplit": 0.8,
        "maxContracts": 2,
        "maxMicroContracts": 20,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 1100,
        "payoutFrequency": "From 2 days",
        "minPayout": "$250",
        "notes": "EOD drawdown · Micro scaling 10:1 · No evaluation consistency rule, but 50% consistency applies once funded · No activation fee · Max payout request: $1,000 · No minimum profit per day"
      },
      {
        "label": "Builder $50k",
        "phase": "eval",
        "size": 50000,
        "maxDrawdown": 2000,
        "drawdownType": "trailing_eod",
        "consistencyPercent": null,
        "profitTarget": 3000,
        "dailyLossLimit": null,
        "minTradingDays": 2,
        "minWinningDays": null,
        "winningDayMinProfit": null,
        "cost": null,
        "profitSplit": 0.8,
        "maxContracts": 4,
        "maxMicroContracts": 40,
        "activationFee": 0,
        "resetFee": null,
        "buffer": 2100,
        "payoutFrequency": "From 2 days",
        "minPayout": "$500",
        "notes": "EOD drawdown · Micro scaling 10:1 · No evaluation consistency rule, but 50% consistency applies once funded · No activation fee · Max payout request: $2,000 · Funded daily drawdown: $1,000"
      }
    ]
  }
]

export function catalogueFor(name: string): FirmCatalogue | undefined {
  const needle = name.trim().toLowerCase()
  return FIRM_CATALOGUES.find(
    (firm) => firm.name.toLowerCase() === needle || firm.slug === needle,
  )
}
