/**
 * Seeds the database.
 *
 * Two modes:
 *   npm run db:seed            reference data only — the firm presets, so the
 *                              account form has something to pick from.
 *   npm run db:seed -- --demo  adds a synthetic account and ~90 days of trades
 *                              so every chart and insight has something to show
 *                              before your real data arrives.
 *
 * The demo account is counted in statistics like any other — an account excluded
 * from every chart would demonstrate nothing. Delete it on the Accounts page
 * before you rely on any number in the app.
 */
import { db } from './index'
import { accounts, executions, expenses, propFirms, subscriptions } from './schema'
import { FIRM_PRESETS } from '../lib/propfirm/rules'
import { rebuildTradesForAccount } from '../server/trades'
import { tradingDayFor } from '../lib/time'

const DEMO = process.argv.includes('--demo')

async function main() {
  console.log('Seeding prop firm presets…')

  const firmIds = new Map<string, number>()
  for (const preset of FIRM_PRESETS) {
    const [row] = await db
      .insert(propFirms)
      .values({
        name: preset.name,
        platform: preset.platform,
        profitSplit: preset.profitSplit,
        payoutPolicy: preset.note,
      })
      .onConflictDoNothing()
      .returning({ id: propFirms.id, name: propFirms.name })
    if (row) firmIds.set(row.name, row.id)
  }
  console.log(`  ${firmIds.size} firms added.`)

  if (!DEMO) {
    console.log('Done. Pass --demo to also generate sample trades.')
    return
  }

  console.log('Generating demo data…')

  const [account] = await db
    .insert(accounts)
    .values({
      label: 'Demo 50k (sample data)',
      platform: 'manual',
      phase: 'eval',
      status: 'active',
      startingBalance: 50_000,
      profitTarget: 3_000,
      maxDrawdown: 2_500,
      drawdownType: 'trailing_eod',
      minTradingDays: 7,
      consistencyPercent: 0.3,
      costBase: 137,
      commissionPerContract: 1.24,
      // Deliberately included in statistics: a demo account that is excluded
      // from every chart demonstrates nothing. The label and the notes make
      // clear what it is, and it should be deleted before real data arrives.
      excludeFromStats: false,
      notes: 'Generated by `npm run db:seed -- --demo`. Delete this account once your real data is in — until then it is counted in every statistic.',
    })
    .returning({ id: accounts.id })

  // A deterministic pseudo-random sequence keeps re-seeds reproducible and
  // avoids a "lucky" or "cursed" demo run.
  let state = 42
  const random = (): number => {
    state = (state * 1664525 + 1013904223) % 4294967296
    return state / 4294967296
  }

  const fills: (typeof executions.$inferInsert)[] = []
  const start = new Date()
  start.setUTCDate(start.getUTCDate() - 90)

  let price = 21_000
  let sequence = 0

  for (let day = 0; day < 90; day++) {
    const date = new Date(start)
    date.setUTCDate(date.getUTCDate() + day)
    // Weekends are closed.
    if (date.getUTCDay() === 0 || date.getUTCDay() === 6) continue
    // Not every weekday is a trading day.
    if (random() < 0.25) continue

    const tradesToday = 1 + Math.floor(random() * 4)

    for (let n = 0; n < tradesToday; n++) {
      const long = random() > 0.45
      const qty = random() > 0.8 ? 2 : 1
      // A positive-expectancy sequence: wins are less frequent but larger.
      const win = random() < 0.42
      const points = win ? 8 + random() * 22 : -(5 + random() * 12)
      const move = long ? points : -points

      const entryPrice = price + (random() - 0.5) * 40
      const exitPrice = entryPrice + move

      const entryAt = new Date(date)
      entryAt.setUTCHours(14 + Math.floor(random() * 6), Math.floor(random() * 60), 0, 0)
      const exitAt = new Date(entryAt.getTime() + (60 + random() * 2400) * 1000)

      const commissionPerSide = (1.24 * qty) / 2

      fills.push(
        {
          accountId: account.id,
          externalId: `demo-${sequence++}`,
          source: 'manual',
          contract: 'MNQZ5',
          symbol: 'MNQ',
          side: long ? 'buy' : 'sell',
          qty,
          fillPrice: Number(entryPrice.toFixed(2)),
          fillAt: entryAt,
          tradingDay: tradingDayFor(entryAt, 'Asia/Jerusalem', '00:00'),
          commission: commissionPerSide,
          fees: 0,
        },
        {
          accountId: account.id,
          externalId: `demo-${sequence++}`,
          source: 'manual',
          contract: 'MNQZ5',
          symbol: 'MNQ',
          side: long ? 'sell' : 'buy',
          qty,
          fillPrice: Number(exitPrice.toFixed(2)),
          fillAt: exitAt,
          tradingDay: tradingDayFor(entryAt, 'Asia/Jerusalem', '00:00'),
          commission: commissionPerSide,
          fees: 0,
        },
      )

      price = exitPrice
    }
  }

  await db.insert(executions).values(fills)
  const built = await rebuildTradesForAccount(account.id)
  console.log(`  ${fills.length} fills → ${built} trades.`)

  await db.insert(expenses).values([
    {
      spentOn: isoDaysAgo(85),
      category: 'eval_fee',
      vendor: 'Demo Firm',
      description: 'Evaluation',
      amount: 137,
      currency: 'USD',
      fxRate: 1,
      amountBase: 137,
      accountId: account.id,
      deductiblePercent: 1,
      vatAmount: 0,
      hasReceipt: true,
    },
    {
      spentOn: isoDaysAgo(60),
      category: 'reset_fee',
      vendor: 'Demo Firm',
      description: 'Reset',
      amount: 85,
      currency: 'USD',
      fxRate: 1,
      amountBase: 85,
      accountId: account.id,
      deductiblePercent: 1,
      vatAmount: 0,
      hasReceipt: true,
    },
  ])

  await db.insert(subscriptions).values([
    {
      vendor: 'TradingView',
      description: 'Premium plan',
      category: 'platform_subscription',
      amount: 59.95,
      currency: 'USD',
      cadence: 'monthly',
      startedOn: isoDaysAgo(90),
      nextRenewalOn: isoDaysAgo(-5),
      deductiblePercent: 1,
    },
    {
      vendor: 'CME Group',
      description: 'Non-professional market data',
      category: 'data_feed',
      amount: 15,
      currency: 'USD',
      cadence: 'monthly',
      startedOn: isoDaysAgo(90),
      nextRenewalOn: isoDaysAgo(-12),
      deductiblePercent: 1,
    },
  ])

  console.log(
    '\nDone. The demo account IS counted in your statistics so the charts have something to show.\n' +
      'Delete "Demo 50k (sample data)" on the Accounts page before you rely on any number here.',
  )
}

function isoDaysAgo(days: number): string {
  const date = new Date()
  date.setUTCDate(date.getUTCDate() - days)
  return date.toISOString().slice(0, 10)
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error)
    process.exit(1)
  })
